### ISSUE TITLE
Horizontal filter component hides the X icon in sds-search

### ISSUE THREAD

**Issue by nishantg95** [GSA/sam-design-system#1001]
**Components Involved**
Horizontal Filter component
**Expected Behavior**
There should be an X icon in the sds-keyword search that should allow to reset search field

**Actual Behavior**
The X icon color gets overridden to white color, making it invisible on white background

**Your Environment**
Angular Version: 12.2.15
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
components: 12.0.5
sam-formly: 12.0.6
sam-styles: 0.0.139

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
Actual:
![image](https://user-images.githubusercontent.com/15683402/178401853-df1b0162-dbf4-48ab-88a0-2e39eb1680a2.png)

Expected:
![image](https://user-images.githubusercontent.com/15683402/178402097-e2169ec1-f40b-419f-b8b1-7b7052524f75.png)

**Comment by yerramshilpa** [comment]
This issue has been resolved and released in @gsa-sam/sam-formly@13.0.6

**Comment by yerramshilpa** [comment]
The issue was resolved in 13.0.6 version
