### ISSUE TITLE
NGX USWDS Basic Table Update

### ISSUE THREAD

**Issue by bserrano1** [GSA/sam-design-system#1011]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
NGX USWDS Table Basic
https://gsa.github.io/ngx-uswds/?path=/story/components-table--basic&args=striped:true;borderless:false;compact:true;stacked:true;stackedHeader:true

**Expected Behavior**
How you expect the listed component(s) to function

Table should not have additional margins added to the top, bottom or right.
![image](https://user-images.githubusercontent.com/26351294/180456324-f7fd769a-804c-46a1-8fa6-1cf3ac74a332.png)

Mobile view should look like the following:
![image](https://user-images.githubusercontent.com/26351294/180456550-5651804e-49eb-4253-96eb-f25b5867f18e.png)

**Actual Behavior**
How the listed component(s) actually function

Current table has default Margin surrounding the table which is causing issues with implementation on our page.
![image](https://user-images.githubusercontent.com/26351294/180232145-6d8f4969-c33b-418a-8f6c-ea4ac278ab1d.png)
![image](https://user-images.githubusercontent.com/26351294/180458086-9d972f29-8c36-4b65-9bd6-97bdddbdab9d.png)

Mobile view looks need changes to match our design mock:
![image](https://user-images.githubusercontent.com/26351294/180457125-65232c1f-8e77-426e-a40d-947d2f4928d6.png)
![image](https://user-images.githubusercontent.com/26351294/180458202-8b6129fe-415c-4bc1-bc02-5034cf271eb9.png)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

Angular Version: "^12.2.15"
GSA Packages: 
@gsa-sam/components@12.0.4
@gsa-sam/sam-material-extensions@12.0.4
@gsa-sam/sam-formly@12.0.4
@gsa-sam/layout@12.0.1
@gsa-sam/layouts@12.0.1
@gsa-sam/ngx-uswds@12.0.0-beta.7
@gsa-sam/ngx-uswds-icons@12.0.0-beta.7
@gsa-sam/sam-styles@0.0.137
@gsa-sam/shared@12.0.1

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

JIRA Ticket: IAEMOD-268

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by cwolf10** [comment]
@bserrano1 sam-styles@0.0.142 contains the fixes for the border issue you were seeing.
