### ISSUE TITLE
Add Hover Over and Clickable Rows to NGX Basic Table

### ISSUE THREAD

**Issue by bserrano1** [GSA/sam-design-system#1012]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is
https://gsa.github.io/ngx-uswds/?path=/story/components-table--basic
Should allow for each row of the table to be clickable with a link. 
Hover over should also be implemented. 

**Describe the desired solution**
SDS_Table currently has this feature already for reference. 
![image](https://user-images.githubusercontent.com/26351294/180480011-8d28923f-cadd-4dbd-9b5f-e53de0a7f0fd.png)

**Describe alternatives you've considered**
Currently using the SDS Table Component for the time being.

**Additional context**

**Comment by cwolf10** [comment]
Addressed with ngx-uswds@12.0.3 & sam-styles@0.0.143
