### ISSUE TITLE
sds-formly-checkbox - Position issue (/padding issue)

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#1013]
**Components Involved**
sds-formly-checkbox-demo
gsa-sam-checkbox-radio  

**Expected Behavior**
The checkboxes should align according to the mockup(without the space in between) and the css should behave according to the dialog 

**Actual Behavior**
The checkboxes are not aligned and not aligning according to the dialog

**Your Environment**
Angular Version: 12.2.15"

**Ticket Number**
IAEMOD-1522

**Additional context**
![image](https://user-images.githubusercontent.com/82841107/180846518-43458ac4-6bde-47bf-a002-3b09d857656d.png)

**Comment by yerramshilpa** [comment]
This issue is resolved in sam-styles@0.0.149 version
