### ISSUE TITLE
Video component issues

### ISSUE THREAD

**Issue by nishantg95** [GSA/sam-design-system#1018]
**Components Involved**
Sds Video component
**Expected Behavior**
Video player should function as expected, even with a complex html/VPConfiguration ID

**Actual Behavior**
Video player fails to load. Issue in continuation of #996 

**Your Environment**
@gsa-sam/components@12.0.8

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-1230

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/15683402/181773542-823f41e0-5c70-43d7-af67-ff19bc03d118.png)

**Comment by nishantg95** [comment]
@cwolf10 I was unable to re-open the last issue, so created a new one referencing the old one

**Comment by cwolf10** [comment]
@nishantg95 sam-design-system@12.0.9 is currently being released. This issue is fixed as a part of that release.
