### ISSUE TITLE
Enhance sds-filters functionality

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1020]
**Is your feature request related to a problem? Please describe.**
For award data, we want to display the nesting of filters in more filters modal in a different way than the 
supported default format.

**Describe the desired solution**
When I use more filters functionality of sds-filters, the more filters modal reflects
the nesting of the filters configured. I should be able to configure how the filters are displayed in more filters column rather than using the nesting from the formly config.

**Describe alternatives you've considered**

**Additional context**

**Comment by cwolf10** [comment]
Stale, please reopen if this issue is still relevant.
