### ISSUE TITLE
Add prefix, suffix support for formly input.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1021]
**Is your feature request related to a problem? Please describe.**
We have a request to implement a currency input, which requires us to prefix the formly input with '$'.

**Describe the desired solution**
Please update formly input to support prefix/suffix similar to ngx-uswds input.
gsa.github.io/ngx-uswds/?path=/story/components-input--basic&args=suffix:

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by yerramshilpa** [comment]
This is available in latest version in ngx-uswds@14.0.0-beta.0
