### ISSUE TITLE
Requred not working on muliti checkbox in formly 

### ISSUE THREAD

**Issue by thomastighe** [GSA/sam-design-system#1025]
Formly multicheckbox
Please list the common component(s) involved that you're experiencing an issue with

**Expected Behavior**
If field is required and you select and then unselect all it is not showing that the field is invalid 
**Actual Behavior**
How the listed component(s) actually function
If field is required and you select and then unselect all it is not showing that the field is invalid 

**Your Environment**
Angular Version: 12
@gsa-sam packages version:12.0.8 (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
Required validation is not straight as simple input, here is the article.The change is also made on the design system side and released in @gsa-sam/sam-formly@12.0.11 version.
Code change of implementation side.
 
###   validators: {
        validation: ['requiredTrue'],
      },
      
      
https://github.com/ngx-formly/ngx-formly/issues/1362
