### ISSUE TITLE
Incorrectly shown deprecation message

### ISSUE THREAD

**Issue by annms2011** [GSA/sam-design-system#1034]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
SdsSideToolbarModule

**Expected Behavior**
How you expect the listed component(s) to function
Import side toolbar from @gsa-sam/components without a warning message in the console

**Actual Behavior**
How the listed component(s) actually function
We get a warning message saying "The side toolbar you are currently using is deprecated. Please instead import SdsSideToolbarModule from @gsa-sam/components" even though that is the module we are using.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

@gsa-sam/components: 12.0.9
Angular Version 12.2.15
@gsa-sam/layout: 12.0.1
@gsa-sam/layouts: 12.0.1
@gsa-sam/ngx-uswds: 12.0.1
@gsa-sam/ngs-uswds-icons: 12.0.0-beta.2
@gsa-sam/sam-formly: 12.0.9
@gsa-sam/sam-material-extensions: 12.0.9
@gsa-sam/sam-styles: 0.0.140
@gsa-sam/shared: 12.0.10

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

IAEMOD-1470

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/88856168/184446889-777f4b89-cc19-4bef-b28a-c6af21e55c4a.png)
![image](https://user-images.githubusercontent.com/88856168/184447187-479b1871-4139-4f2e-b412-be848853c1f2.png)

**Comment by yerramshilpa** [comment]
The issue has been resolved in @gsa-sam/components@12.0.4 version
