### ISSUE TITLE
Accessibility issue for formly-form - aria-describedby

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1037]
**Components Involved**
formly-form

**Expected Behavior**
Adding a "description" config will generate accessibility compliant tags

**Actual Behavior**
I am seeing an error during WAVE testing for the aria-describedby tag: "An aria-labelledby or aria-describedby reference exists, but the target for the reference does not exist."

**Your Environment**
Angular Version: 12.2
@gsa-sam packages version: 12.0.10, @gsa-sam/ngx-uswds@12.0.2

**Ticket Number**
IAEMOD-2859

**Additional context**

WAVE result:
![image](https://user-images.githubusercontent.com/75684861/184675085-086f65c5-6f3a-472d-be7a-2175b74e9704.png)

FormlyFieldConfig:
![image](https://user-images.githubusercontent.com/75684861/184675134-368aa128-b32b-41c7-8cdc-baec4cfde530.png)

HTML output:
![image](https://user-images.githubusercontent.com/75684861/184675164-b3b07dfe-f589-4ae5-b69e-de474ca21cf3.png)

**Comment by cwolf10** [comment]
This issue is addressed in v12.0.13.
