### ISSUE TITLE
Video component displays browser controls instead of SDS controls

### ISSUE THREAD

**Issue by nishantg95** [GSA/sam-design-system#1048]
**Components Involved**
sds-video-player

**Expected Behavior**
Video player should show custom controls for playback as set by sds video player configuration

**Actual Behavior**
1) Video player shows default Chrome video player controls

2) New incorrect player does not show captions control on the MFE. Not sure if there were changes made to VPConfiguration for which the communication was missed.

**Your Environment**
@gsa-sam/components: 12.0.9
@gsa-sam/styles: 0.0.140

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
[IAEMOD-4282](https://cm-jira.usa.gov/browse/IAEMOD-4282)

**Additional context**
Expected behavior:
![image](https://user-images.githubusercontent.com/15683402/189969503-2f44f765-d09c-43a1-bfdf-c3d1bc53d584.png)

Actual Behavior:
![image](https://user-images.githubusercontent.com/15683402/189969845-f6d9abbf-aff1-40ec-b9d7-26d9dcace7bd.png)

MFE missing captions option, even though vtt file is being downloaded by the browser
![image](https://user-images.githubusercontent.com/15683402/189971945-60cc7b37-aa39-474e-874e-6efa44d273f0.png)

Sds library example still shows captions unlike MFE
![image](https://user-images.githubusercontent.com/15683402/189972324-3f412699-8ccc-4742-8dc6-94d4e595a2d7.png)

**Comment by cwolf10** [comment]
This fix was released with SDS@12.0.14
