### ISSUE TITLE
Formly Accordion Wrapper Error

### ISSUE THREAD

**Issue by cwolf10** [GSA/sam-design-system#1049]
**Components Involved**
component - FormlyAccordianFormFieldComponent
demo - GroupAccordion

**Expected Behavior**
The component should load and not error.

**Actual Behavior**
<img width="1444" alt="Screen Shot 2022-09-14 at 8 54 40 AM" src="https://user-images.githubusercontent.com/72805180/190160387-7ed75a5b-96be-4d9b-aa4d-f91a94622b7a.png">

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: 12.0.12 (Please list individually if all packages are not same version)

**Comment by yerramshilpa** [comment]
This wrapper demo has been removed and no longer using the wrapper
