### ISSUE TITLE
Tree Table 508 <tr> issue

### ISSUE THREAD

**Issue by bserrano1** [GSA/sam-design-system#1050]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
Tree-table component
https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/site/gsa/sam-design-system/documentation/components/tree-table/examples

**Expected Behavior**
How you expect the listed component(s) to function
Component is functioning correctly but is setting up 508 issue with the tool Access Assistant. 

**Actual Behavior**
How the listed component(s) actually function
Issue seems to revolve around role associated with the <tr> tag.
![image](https://user-images.githubusercontent.com/26351294/190229340-773add84-0b0e-4e95-8c51-bb00682e4f05.png)
![image](https://user-images.githubusercontent.com/26351294/190229480-150cc810-342c-46ef-8175-929294a3416a.png)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
Angular Version: 12.2.15
@gsa-sam/components: 12.0.12
@gsa-sam/layout: 12.0.1
@gsa-sam/layouts: 12.0.1
@gsa-sam/ngx-uswds: 12.0.3
@gsa-sam/ngx-uswds-icons: 12.0.0-beta.2
@gsa-sam/sam-formly: 12.0.12
@gsa-sam/sam-material-extensions: 12.0.12
@gsa-sam/sam-styles: 0.0.143
@gsa-sam/shared: 12.0.1

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ
IAEMOD-3851

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
The issue has been resolved in @gsa-sam/components@13.0.2 version
