### ISSUE TITLE
Filter Sidenav not resetting after clicking apply and reopening in tablet/mobile view

### ISSUE THREAD

**Issue by yasminmenchaca** [GSA/sam-design-system#1061]
**Components Involved**
Filter Sidenav

**Expected Behavior**
Allow user to reset the filter after clicking apply, reopening the filter then clicking on "reset"

**Actual Behavior**
After clicking apply when the user makes their checkbox selections and/or searches by text then reopens the filter and clicks "reset", the filter will not uncheck selections and clear the text chips. Manually clearing out selections/chips then clicking reset will reselect and populate the chips. A demonstration is included below.

**Your Environment**
![Screen Shot 2022-10-19 at 1 14 58 PM](https://user-images.githubusercontent.com/57374092/196772147-62eeab0d-bd5d-4ef9-bdd2-6759cfa0a476.png)
![Screen Shot 2022-10-19 at 1 15 13 PM](https://user-images.githubusercontent.com/57374092/196772233-3a48b79a-7847-4c70-bbe7-90a33e234651.png)

**Ticket Number**
IAEMOD-5561

**Additional context**

https://user-images.githubusercontent.com/57374092/196787178-8074a657-fbea-461b-8aba-59fd8876d7c3.mov

**Comment by yerramshilpa** [comment]
@yasminmenchaca This issue can be resolved using the input to pass the  [defaultModel]="defaultModel", if you have any default filter you can pass else pass an empty model for the default. Let me now if this resolve the issue
