### ISSUE TITLE
sam-checkbox is not allowing to input secondary label (options)

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#1065]
**Components Involved**
sam-checkbox

**Expected Behavior**
Allow secondary label will allow to implement the line break(please refer the attached screenshot)

**Actual Behavior**
Allow only one label input with the options

**Your Environment**
Angular Version: 12 and 13
@gsa-sam packages version:  (Please list individually if all packages are not same version)

**Ticket Number**
IAEMOD - 6303

**Additional context**

![unnamed](https://user-images.githubusercontent.com/82841107/199822144-53984ea4-8952-4459-99f9-02be59f53dbb.png)

![unnamed](https://user-images.githubusercontent.com/82841107/199822491-325aab1a-cfc3-4f90-8b87-cd6156f1dd0b.png)

![unnamed](https://user-images.githubusercontent.com/82841107/199822515-d1bda451-12c5-41f0-ac41-47b51262aa8e.png)

![unnamed](https://user-images.githubusercontent.com/82841107/199822662-c985a91d-e097-4692-8a96-7f2735122cf4.png)

![unnamed](https://user-images.githubusercontent.com/82841107/199822722-c3d93f1f-5955-4197-a9ab-e6ccff4f8f41.png)

**Comment by yerramshilpa** [comment]
The feature is implemented and released sam-ui-elements@5.0.0-beta-1
