### ISSUE TITLE
SDS - Actions Menu Dropdown - Safari Browser Does Not Tab To Actions Buttons

### ISSUE THREAD

**Issue by rpsboyz** [GSA/sam-design-system#1079]
**Components Involved**
Actions Menu Dropdown

**Expected Behavior**
When using any valid web-browser (Chrome, Edge, Safari, etc.), and navigating to the 'Actions (dropdown)' section on the Design Systems Components page, when user tabs within the 'Actions Menu Dropdown' portion it should tab to the Actions buttons.

**Actual Behavior**
When navigating to the 'Actions (dropdown)' section on the Design Systems Components page, when tabbing in the 'Actions Menu Dropdown' portion it does not tab to the Actions buttons using Safari browser (works fine with Chrome and Edge). I had other team members verify this as well. This affects the MFE - Large Downloads page in Safari.

**Your Environment**
<img width="137" alt="image" src="https://user-images.githubusercontent.com/49442068/205344150-56541269-3136-4895-8741-ba5af2c42bcf.png">

**Ticket Number**
Jira Ticket for tracking is: IAEMOD-5576

**Additional context**
Audio/video recording linked in Jira ticket

**Comment by yerramshilpa** [comment]
@rpsboyz  the issue with Safari setting not with the component, change the setting of the safari 
Go to “Preferences”
Select the “Advanced” tab
<img width="1187" alt="Screenshot 2023-04-04 at 12 47 40 AM" src="https://user-images.githubusercontent.com/44271677/229797499-066ca129-8c60-4261-90a6-c12509c56d61.png">

Check “Press Tab to highlight each item on a webpage”
