### ISSUE TITLE
date-picker validation date format does not match the input format 

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#1097]
Components Involved
formly of type 'date-picker'

Expected Behavior
The validation should be of the same date format as what is passed into the date-picker config

Actual Behavior
Date is shown in the format of Jan 19, 2023, but the validation is showing in the format of 1/19/2023
<img width="1074" alt="Screen Shot 2023-01-17 at 11 30 23 AM" src="https://user-images.githubusercontent.com/74928453/212973703-c38a0acf-1f23-4c28-9154-4eed9c118465.png">

Your Environment
Angular Version: 13.3.11
 "@gsa-sam/components": "13.0.4",
    "@gsa-sam/layout": "13.0.0-beta.1",
    "@gsa-sam/layouts": "13.0.0-beta.0",
    "@gsa-sam/ngx-uswds": "13.0.0-beta.1",
    "@gsa-sam/ngx-uswds-icons": "13.0.0-beta.2",
    "@gsa-sam/sam-formly": "13.0.4",
    "@gsa-sam/sam-material-extensions": "13.0.4",
    "@gsa-sam/sam-styles": "0.0.149",
    "@gsa-sam/shared": "13.1.3",

Ticket Number
IAEDEV-4878

Additional context

Code used for configuring the date-picker;
{
key: 'endDate',
type: 'datepicker',
templateOptions: {
label: 'End Date',
hideOptional: true,
required: true,
minDate: new Date(),
placeholder:
'eg: ' +
new Date().toLocaleString('en-US', {
month: 'short',
day: 'numeric',
year: 'numeric',
}),
},
}

**Comment by yerramshilpa** [comment]
Issue resolved in @gsa-sam/sam-formly@13.0.5 version
