### ISSUE TITLE
usa-accordion Component Update to Match Design Mock Behaviour

### ISSUE THREAD

**Issue by Sunset05** [GSA/sam-design-system#1098]
**Is your feature request related to a problem? Please describe.**
The multiselectable usa-accordion component is not able to display the expected look and feel of given mock design images

Given-mock-design:
![image](https://user-images.githubusercontent.com/77186128/213284932-76880720-216a-462c-aebd-fb3beb72a4bf.png)

**Describe the desired solution**
The component needs to be able to have a single border down the center of the entire expandable content section.
The icon of the dropdown selection should be able to support chevrons instead of '+/-' icons

**Describe alternatives you've considered**
I have implemented extensive overrides to the markup of the component, but am finding it increasingly difficult to further customize this component with custom SCSS to match the given mock design

Working-changes:
![image](https://user-images.githubusercontent.com/77186128/213297703-0e48212e-7244-4e0c-851a-615ef557b70a.png)

**Additional context**
When expanded, the title of the provision should turn blue
there is a border-bottom being automatically added by the expanded accordion

**Comment by davereed** [comment]
Based on feedback from the designers, we are suggesting to use the collapse component and follow the design provided. Please feel free to reach out with any questions.
