### ISSUE TITLE
Tool Tip needs to be flexible and expand beyond the white page/container

### ISSUE THREAD

**Issue by navyasreekumbam-reisys** [GSA/sam-design-system#1099]
**Components Involved**
sds-tooltip
**Expected Behavior**
Tool Tip should be flexible and expand beyond the white background of the page
**Actual Behavior**
Tool tip is cut off

**Ticket Number**
IAEMOD-8624

![image](https://user-images.githubusercontent.com/55297909/213378220-c5a34bf3-bc54-4315-a295-7e2731e360eb.png)

![image](https://user-images.githubusercontent.com/55297909/213378279-d73354c3-6058-42cb-b13a-51ca2c10145a.png)

**Comment by yerramshilpa** [comment]
Issue resolved in @gsa-sam/sam-styles@0.0.150 version
