### ISSUE TITLE
Video Player Captions not pulling from S3

### ISSUE THREAD

**Issue by annms2011** [GSA/sam-design-system#1103]
**Components Involved**
Video Player

**Expected Behavior**
How you expect the listed component(s) to function
Closed Captions should show when selected

**Actual Behavior**
How the listed component(s) actually function
An error occurs when pulling the captions from S3

**Your Environment**
Angular Version: 13.3.11
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
@gsa-sam/components: 13.0.4
@gsa-sam/layout: 13.0.0-beta.1
@gsa-sam/layouts: 13.0.0-beta.0
@gsa-sam/ngx-uswds: 13.0.0-beta.1
@gsa-sam/ngx-uswds-icons: 13.0.0-beta.2
@gsa-sam/sam-formly: 13.0.4
@gsa-sam/sam-material-extensions: 13.0.4
@gsa-sam/sam-styles: 0.0.148
@gsa-sam/shared: 13.1.1

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-9282

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

When pulling captions file from S3, we get an error. The correct file is pulled and will open if you click on the link, but will not load into the captions. 
![image](https://user-images.githubusercontent.com/88856168/214112299-438e14d7-1cd7-4d34-8152-4a11f448e586.png)

**Comment by cwolf10** [comment]
I was able to recreate the issue in our component, but unable to resolve by updating crossorigin attribute. That points to the issue being with the S3 bucket, and not with the video-player component. An update is needed on the S3 bucket to allow for a less restrictive CORS policy to allow the resource to be loaded.
