### ISSUE TITLE
508 - SDS- Stepper - Previous, Close, Save and Save and Continue buttons

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#1119]
Components Involved
SDS-Stepper

Expected Behavior
Wave (508 testing tool) should not show any error on Previous, Close, Save and Save and Continue buttons

Actual Behavior
Wave tool shows "Empty Button" error on Previous, Close, Save and Save and Continue buttons.

Your Environment
Angular Version: 13.3.11

Ticket Number
IAEMOD-401

![image](https://user-images.githubusercontent.com/82841107/217643373-2cfb6805-bde0-4751-baec-6295f385ee6d.png)

![image](https://user-images.githubusercontent.com/82841107/217643419-ed2a393d-8b31-4228-aea9-bf4d0124a00e.png)

**Comment by yerramshilpa** [comment]
@Parulbpatel  this is not related to sds-steppers, it's part of the layout stepper from the wizard team.
