### ISSUE TITLE
508 - Tree Table not reading data

### ISSUE THREAD

**Issue by addiedavis** [GSA/sam-design-system#1123]
**Components Involved**
Tree Table as seen in https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.sites.pages.cloud.gov/site/gsa/sam-design-system

**Expected Behavior**
1) open the tree table
2) tab into the first item (that has children)
3) hit the enter key -> expands to view children
4) tab into first child 
5) reads the first child when using chrome's screen reader ( https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn/related?hl=en )

**Actual Behavior**
1) open the tree table 
2) tab into the first item (that has children) 
3) hit the enter key -> expands to view children
4) tabs into second child. It skips over any child that doesn't have grandchildren of the initial parent. It does not read any children that are childless 

**Your Environment**
Angular Version: 13.3.11
@gsa-sam/components@13.0.3
@gsa-sam/layout@13.0.0.-beta.1
@gsa-sam/layouts@13.0.0-beta.0
@gsa-sam/ngx-uswds@13.0.0-beta.1
@gsa-sam/ngx-uswds-icons@13.0.0-beta.2
@gsa-sam/sam-formly@13.0.3
@gsa-sam/sam-material-extensions@13.0.3
@gsa-sam/sam-styles@0.0.147
@gsa-sam/shared@13.1.10

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-9640

**Additional context**
![image](https://user-images.githubusercontent.com/32769685/218766940-d3839c52-9ea4-4c61-8eb0-0f9719eb65ef.png)

![image](https://user-images.githubusercontent.com/32769685/218767079-53f77cbc-9e9a-470a-8ba5-e80d7dbf0154.png)

![image](https://user-images.githubusercontent.com/32769685/218767203-a75b1e71-3f5d-4391-836b-5a2ef71e91c7.png)

![image](https://user-images.githubusercontent.com/32769685/218767438-677579c6-b755-4e0e-8f4b-f4172a3461c3.png)

**Comment by davereed** [comment]
@addiedavis can you confirm that this is happens using JAWS w/ Chrome? We don't support/test with the addon software you link to. Thanks.

**Comment by addiedavis** [comment]
Hi @davereed,
The original JIRA ticket is with JAWS, the chrome was mainly mentioned because it is also a problem there.

**Comment by addiedavis** [comment]
Hi @davereed ,

Checking in. 
Is there an estimated time when this component will be looked at?

**Comment by cwolf10** [comment]
Hey @addiedavis, adding an `href="javascript:void(0)"` on to this [anchor tag](https://github.com/GSA/sam-design-system/blob/master/libs/documentation/src/lib/storybook/tree-table/tree-table-basic/tree-table-basic.component.html#L16) resolved the issue in my local. Could you give that a try and let me know if that resolves the issue you are seeing?

**Comment by addiedavis** [comment]
I will relay this to the E360 team - I made this ticket while I was helping out while people were on paternity leave

**Comment by cwolf10** [comment]
Demo has been updated to show how to fix the issue noted above: https://gsa.github.io/sam-design-system/?path=/story/components-tree-table--basic
