### ISSUE TITLE
Expand icon in table is taking extra space.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1129]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
SDS Table

**Expected Behavior**
How you expect the listed component(s) to function
Expand icon should not overflow out of the column

**Actual Behavior**
How the listed component(s) actually function
Expand icon is overflowing out of the column
![image](https://user-images.githubusercontent.com/92172714/220645122-4aa8d6f1-7f68-4153-89d6-e31d226b3f0f.png)

**Your Environment**
Angular Version: 13.3.11
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/92172714/220645906-627d22b0-b341-41bc-a1c2-78a7db83e3bb.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-10873

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
@knamburigsa This is the expected extra space added to move the icon little closer to the first column.

**Comment by yerramshilpa** [comment]
Issue is resolved in @gsa-sam/sam-material-extensions@14.0.3
