### ISSUE TITLE
SDS-Toast component does not support injecting HTML

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1133]
**Components Involved**
Toast Component.
https://github.com/GSA/sam-design-system/blob/master/libs/packages/components/src/lib/toast/toast-single.component.html#L6
**Expected Behavior**
How you expect the listed component(s) to function
When I configure(enableHtml: true) the toast component to show html, toast should display html rather than sanitizing it.
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr-config.ts#L51

**Actual Behavior**
How the listed component(s) actually function
Even though I configure the toast component to display html  it sanitizes the html and shows as text.
![image](https://user-images.githubusercontent.com/92172714/222487054-d49591a5-acdd-4a5f-b41e-4969788421cc.png)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/92172714/222487377-f80d0950-091d-435f-9867-a0bb26ab177f.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-1445

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

sds-toast component is directly using message in the template and angular is sanitizing it.
if enableHtml is set to true we need to set the message to innerHtml . The message will already be sanitized by ngx-toastr.

sds-toast component ignores the title, is this intentional?

**Comment by davereed** [comment]
See example component:
https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts#L39

**Comment by cwolf10** [comment]
And Github closed this on merging... A fix for this has been merged to master, will update this thread when a new version is released with this fix.

**Comment by cwolf10** [comment]
This should have been fixed in a previous version as there have been many releases since my last comment.
