### ISSUE TITLE
Disable option for Action Dropdown Menu button 

### ISSUE THREAD

**Issue by vduggireddy-gsa** [GSA/sam-design-system#1135]
**Components Involved**
sds-actions-menu

**Describe the desired solution**
Should be able to disable the button based on an attribute `disable`. 

![image](https://user-images.githubusercontent.com/127118236/223134174-cd75aa95-18d3-4541-ab1d-06d67fd40e6f.png)

**Comment by yerramshilpa** [comment]
Added new feature to disable action menu and releaded in @gsa-sam/components@13.0.7 version
