### ISSUE TITLE
Checbox is cutoff when it is added as last item in samFormalyDialog

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1147]
**Components Involved**
SdsFormlyDialogModule, Checkbox

**Expected Behavior**
Checkbox should be cut off when added sdsFormlyDialog.

**Actual Behavior**
Bottom part of checkbox is cutoff in sdsFormlyDialog.
 I was able to reproduce this sam-design-systems website.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/92172714/228401705-92290bf5-c5c8-4174-8cc6-c12d440fc290.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-4083

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/92172714/228401469-e3e113a9-f75b-4cfe-acb5-7c6b8733596c.png)
Stackblitz: https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.sites.pages.cloud.gov/site/gsa/sam-design-system/assets/stackblitzes/download/download/stackblitz.html

**Comment by yerramshilpa** [comment]
The fix is released in @gsa-sam/sam-formly@14.0.0-beta.1
