### ISSUE TITLE
tooltip icon showing below label for [formly type: 'input']

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#1164]
**Components Involved**
FormlyFieldConfig of type 'input'

**Expected Behavior**
Expecting the tooltip icon to show on the same line as label

**Actual Behavior**
tooltip is showing under label, because of top margin 

**Your Environment**
Angular Version: 14.3.0
"@gsa-sam/components": "14.0.0-beta.1",
"@gsa-sam/layout": "14.0.0-beta.5",
"@gsa-sam/layouts": "14.0.0-beta.2",
"@gsa-sam/ngx-uswds": "14.0.0-beta.2",
"@gsa-sam/ngx-uswds-icons": "14.0.0-beta.2",
"@gsa-sam/sam-formly": "14.0.0-beta.1",
"@gsa-sam/sam-material-extensions": "14.0.0-beta.1",
"@gsa-sam/sam-styles": "0.0.151",
"@gsa-sam/shared": "14.0.0-beta.5",

**Ticket Number**
IAEMOD-14273

**Additional context**

When adding tooltip to formly field of input, the icon is added with a margin-top-3 that is causing the icon is display below the label. When inspecting the element in Chrome and removing the margin-top-3, the icon shows on the same line as label. 

<img width="1358" alt="Screen Shot 2023-04-28 at 12 25 50 PM" src="https://user-images.githubusercontent.com/74928453/235216227-cf623c00-b9df-4d31-9345-21ec0ef7d06a.png">
<img width="1370" alt="Screen Shot 2023-04-28 at 12 26 36 PM" src="https://user-images.githubusercontent.com/74928453/235216249-c8faf3d4-4c61-40b4-8400-4b8eb1c6b91f.png">
<img width="787" alt="Screen Shot 2023-04-28 at 12 27 56 PM" src="https://user-images.githubusercontent.com/74928453/235216278-0e58ecda-b8cc-46e4-87bf-dd3dcf14e439.png">

**Comment by yerramshilpa** [comment]
The fix released in @gsa-sam/sam-formly@14.0.0-beta.2 version

**Comment by yerramshilpa** [comment]
The issue resolved and released in @gsa-sam/sam-formly": "14.0.0-beta.3 version
