### ISSUE TITLE
Multiple search icons are displayed for search button in sds-search component.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1180]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-search 

**Expected Behavior**
How you expect the listed component(s) to function
Only one search button should be displayed.

**Actual Behavior**
How the listed component(s) actually function
Multiple search icons are displayed when the size property is not large. https://github.com/GSA/sam-design-system/blob/angular-14/libs/packages/components/src/lib/search/search.component.ts#L19
![image](https://user-images.githubusercontent.com/92172714/236857445-bec2756f-acee-42db-a78f-2c557f05ea8b.png)

Search icon background image is being added in addition to search icon when the size is not large.
![image](https://user-images.githubusercontent.com/92172714/236858164-af4b32ec-f02d-47ce-a1e3-890f87bf83af.png)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/92172714/236857156-a850c05c-447d-4962-8631-fb7f59113a66.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
Issue has been resolved and released new version for @gsa/ngx-uswds@14.0.0-beta.3 version
