### ISSUE TITLE
Formly Autocomplete - Update model on blur for single select when free text is enabled

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1182]
**Components Involved**
Formly autocomplete

**Expected Behavior**
When free text is enabled on a single select, the model should be updated on blur to save the user's input.

**Actual Behavior**
I have to press the Enter/Return key on the keyboard for the model to be updated and for my data to be saved.

**Your Environment**
Angular Version: 14.3.0
@gsa-sam packages version:
"@gsa-sam/components": "14.0.0-beta.1",
"@gsa-sam/layout": "14.0.1",
"@gsa-sam/layouts": "14.0.0-beta.2",
"@gsa-sam/ngx-uswds": "14.0.0-beta.2",
"@gsa-sam/ngx-uswds-icons": "14.0.0-beta.2",
"@gsa-sam/sam-formly": "14.0.0-beta.1",
"@gsa-sam/sam-material-extensions": "14.0.0-beta.1",
"@gsa-sam/sam-styles": "0.0.151",
"@gsa-sam/shared": "14.0.1"

**Ticket Number**
IAEMOD-14574

**Additional context**

Settings:
<img width="558" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/165dea63-9950-4656-ad72-f354ab89f0b9">

**Comment by yerramshilpa** [comment]
Issue is resolved in @gsa-sam/components@14.0.3 version
