### ISSUE TITLE
The text inside of the Green Chip is overlapping the "X" Button

### ISSUE THREAD

**Issue by HectorMoralesGSA** [GSA/sam-design-system#1271]
**Components Involved**
sds-side-toolbar

**Expected Behavior**
When I enter a long keyword search in this filter, the text inside of the green tag should never overlap the "X" button. The "X" button closes out the green tag when clicked on.

**Actual Behavior**
When I enter a long keyword search in this filter, the text inside of the green tag overlaps and covers the "X" button. The "X" button closes out the green tag when clicked on. When the "X" button is easy to miss when the text overlaps/covers it. Please see attached screenshots for reference. 

**Your Environment**
Angular Version: 14
@gsa-sam packages version: "@gsa-sam/sam-formly": "^14.0.1"

**Ticket Number**
IAEMOD-17611

**Additional context**
In the sds-side-toolbar, we are using the type of "autocomplete" for keyword searches in order for the green "chips" to appear. Please see the attached screenshot for reference of the UI bug. It must be a long keyword search in order for this bug to happen. It also depends on how long the words are. 

![ReferenceScreenshot_GithubIssue](https://github.com/GSA/sam-design-system/assets/133677859/8433310e-aaf3-45e1-a095-eb7b8661d4e3)

**Comment by yerramshilpa** [comment]
Issue is resolved in @gsa-sam/components@14.0.3 version
