### ISSUE TITLE
Disabled Action Menu w/ Label gets smaller on hover

### ISSUE THREAD

**Issue by cwolf10** [GSA/sam-design-system#1272]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
SdsActionsMenuComponent

**Expected Behavior**
How you expect the listed component(s) to function
The button should either have some other color change to indicate hover or do nothing like standard buttons

**Actual Behavior**
How the listed component(s) actually function
The border of the menu button is removed.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam/components@14.0.0-beta.2

**Comment by yerramshilpa** [comment]
Issue resolved in below versions

[@gsa-sam/sam-styles](https://www.npmjs.com/package/@gsa-sam/sam-styles) 3.0.11
[@gsa-sam/components](https://www.npmjs.com/package/@gsa-sam/components) 15.0.1
