### ISSUE TITLE
Disabling ActionMenu w/ label  does not override active state

### ISSUE THREAD

**Issue by cwolf10** [GSA/sam-design-system#1317]
**Components Involved**
SdsActionMenu w/ label

**Expected Behavior**
Clicking on a disabled action menu should not cause any change in the component's rendering.

**Actual Behavior**
When I click a disabled action menu with a label the background turns blue.

**Your Environment**
SAM@15.0.1

**Comment by yerramshilpa** [comment]
Released in sam-styles@0.0.139 version
