### ISSUE TITLE
Sds-stepper  issue with Angular 15 upgrade

### ISSUE THREAD

**Issue by surendranekkanti** [GSA/sam-design-system#1329]
**Components Involved**
SDS-Stepper

**Expected Behavior**
To load the stepper with all the steps and the corresponding child steps

**Actual Behavior**
Child steps and the fields  does not load properly

**Your Environment**
Angular Version:  15.2.9

"@gsa-sam/layout": "^15.0.3",
"@gsa-sam/layouts": "^15.0.4",
"@gsa-sam/ngx-uswds": "^15.0.0",
"@gsa-sam/ngx-uswds-icons": "^15.0.0",
"@gsa-sam/sam-formly": "^15.0.2",
"@gsa-sam/sam-material-extensions": "^15.0.2",
"@gsa-sam/sam-styles": "^3.0.12",
"@gsa-sam/shared": "^15.0.3",

**Ticket Number**
IAEMOD-20812

**Additional context**

![SDSStepper-Angular-15](https://github.com/GSA/sam-design-system/assets/64421489/af18e052-34e0-43d6-a650-ce9a2553806c)

**Comment by brandydanner-gsa** [comment]
@yerramshilpa We are seeing the same issue with the Entity MFE Entity Registration modules where we have a custom stepper that extends `SdsStepper` directly.  We are not using a stepper from the layouts package.

The child steps are not displaying.

Comp / Angular 14:
<img width="255" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/19373515-c8c6-4e1c-a172-2801113911ad">

Local / Angular 15:
<img width="261" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/a94451a5-0cdc-4a83-be2a-3cd9f70debce">

**Comment by cwolf10** [comment]
Resolved with SDS@15.0.3
