### ISSUE TITLE
Need a enhancement for input component with eye Icon with click events to support feature 19153

### ISSUE THREAD

**Issue by NikhithaReddyG** [GSA/sam-design-system#1345]
**Is your feature request related to a problem? Please describe.**
As part of the IAEMOD-19153 feature input fields needs icon inside the component as part of new design currently prefix and suffix on ngx-uswds inputs, but I think it only supported strings

**Describe the desired solution**
On click of eye icon should need onclick event that open model and proceed further steps

**Describe alternatives you've considered**
Plan B will adding a eye icon next to input which similar current SFE.

**Additional context**

![image](https://github.com/GSA/sam-design-system/assets/34350287/f25d9255-a43d-4567-b9e2-f7ed49d61373)

**Comment by yerramshilpa** [comment]
The feature released in sam-formly@16.0.10
