### ISSUE TITLE
SidenavToolbar and SideNavigation Component Enhancements

### ISSUE THREAD

**Issue by Sunset05** [GSA/sam-design-system#1347]
**Is your feature request related to a problem? Please describe.**
This issue is related to IAEMOD-21391. We need to implement the sidenavToolbar as a wrapper to the sideNavigation component in order to display the side navigation at all views.

We were given mocks for the presentation of the sidenav at table and mobile that doesn't seem to be supported by the current configurations available on the component.

SdsSideNavToolbarComponent, SdsSideNavgiationComponent

**Describe the desired solution**
At tablet and mobile view the component needs to be able to be responsive the full width of the screen. On tablet the component is stuck at button size

**Describe alternatives you've considered**
I have tried styling the wrapper explicitly through custom css.

**Additional context**
![mobile-sidenav](https://github.com/GSA/sam-design-system/assets/77186128/124db8b1-faca-4198-a64b-c97bf0c53a1c)
![tablet-sidenav](https://github.com/GSA/sam-design-system/assets/77186128/44aacbb9-8571-45be-999a-d5c96337dcd5)
![wrapper-html](https://github.com/GSA/sam-design-system/assets/77186128/e327ef68-67b6-4668-b5b7-2c51b8acea19)

**Comment by AmabelAntwi** [comment]
@yerramshilpa are there any updates on this ticket?

**Comment by yerramshilpa** [comment]
@AmabelAntwi  This enhancement will be available in the next release.

**Comment by yerramshilpa** [comment]
@AmabelAntwi @Sunset05 the new changes are available in 16.0.16 version
