### ISSUE TITLE
Highlight/change the color of the row in the table

### ISSUE THREAD

**Issue by BhardwajManasvi** [GSA/sam-design-system#1349]
![image](https://github.com/GSA/sam-design-system/assets/108351900/db4423fa-9d20-41fd-b326-aafbfa77a08d)

**Is your feature request related to a problem? Please describe.**
As part of the IAEMOD-15727 Story the requirement i have is to change the color of a row if NAICS codes are updated/changed.

**Describe the desired solution**
can we have a feature of changing the color of a row in the table.

**Comment by cwolf10** [comment]
PR: https://github.com/GSA/sam-design-system/pull/1377
Demo: https://gsa.github.io/sam-design-system/?path=/story/components-table--custom-classes

**Comment by cwolf10** [comment]
Re-opening until the next SDS release.

**Comment by cwolf10** [comment]
Resolved with v16.0.9. See the link below for how to attach custom classes to table row.

https://gsa.github.io/sam-design-system/?path=/story/components-table--custom-classes
