### ISSUE TITLE
disableSubmitButton should works only in initial load of component with checkbox

### ISSUE THREAD

**Issue by NikhithaReddyG** [GSA/sam-design-system#1358]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with

https://github.com/GSA/sam-design-system/blob/6aa998bae5d629dee6f076ee0b9fb164eebb5c02/libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.ts#L39

**Expected Behavior**
disableSubmitButton should works as expected with checkbox as well.

**Actual Behavior**
disableSubmitButton should works only in initial load of component

**Your Environment**
Angular 15 and 16
**Ticket Number**
[Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ](https://cm-jira.usa.gov/browse/IAEMOD-23018)

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://github.com/GSA/sam-design-system/assets/34350287/c3e9830c-cc2b-4356-8270-99be1fec69d9)

**Comment by yerramshilpa** [comment]
Issue resolved in @gsa-sam/sam-formly": "16.0.7"

**Comment by yerramshilpa** [comment]
Fix resolved in @gsa-sam/sam-formly": "16.0.14"
