### ISSUE TITLE
(Angular 16 / Formly V6) Formly Filters - Clicking X to clear field does not fire change event

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1360]
**Components Involved**
sds-filters

**Expected Behavior**
On an "input" type filter, clicking the X to clear the field should fire the "change" event.

**Actual Behavior**
On an "input" type filter, clicking the X to clear the field does not fire the "change" event.

**Your Environment**
Angular Version: 16.2.12
@gsa-sam packages version:
    "@gsa-sam/components": "16.0.5",
    "@gsa-sam/layout": "16.0.2",
    "@gsa-sam/layouts": "16.0.0",
    "@gsa-sam/ngx-uswds": "16.0.1",
    "@gsa-sam/ngx-uswds-icons": "16.0.0",
    "@gsa-sam/sam-formly": "16.0.5",
    "@gsa-sam/sam-material-extensions": "16.0.5",
    "@gsa-sam/sam-styles": "3.0.13",
    "@gsa-sam/shared": "16.0.2",

**Ticket Number**
IAEMOD-21463

**Additional context**
<img width="596" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/57622cbf-d9c2-47a4-9e45-5796bbbcb6ff">

**Comment by yerramshilpa** [comment]
Issue resolved in @gsam-sam/sam-formly@16.0.6 version
