### ISSUE TITLE
Reset Filters is not working as expected when using tabs in mobile mode.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1362]
url: https://gsa.github.io/sam-layouts/?path=/story/responsive-layout--responsive-layout
Steps to reproduce:
1. Navigate to https://gsa.github.io/sam-layouts/?path=/story/responsive-layout--responsive-layout
2. Set the browser in mobile mode. 
![image](https://github.com/GSA/sam-layouts/assets/92172714/35f5a3ab-b85c-48b9-ba05-67c7dd805918)

3. Click on advanced search.
4. Add a chip to the keywords: 'test'.
5. Click apply.
6. Click on advanced search again.
7. Click on reset.
8. The chips are not removed.

https://github.com/GSA/sam-layouts/assets/92172714/4ed102a4-45e6-452c-ba28-85811e842a9c

Expected:
The form should be reset and chips should be removed.

**Comment by yerramshilpa** [comment]
Issue resolved in @gsam-sam/sam-formly@16.0.6 version
