### ISSUE TITLE
Clear marks of input fields move after refreshing a page

### ISSUE THREAD

**Issue by wonko-gsa** [GSA/sam-design-system#1386]
**Components Involved**
`X` (=Clear mark) in input field. 

**Expected Behavior**
It should be located in the same place after refreshing the page. 

**Actual Behavior**
It moved to the front of input field. 

**Your Environment**
Angular Version: 16.2.12
@gsa-sam packages version: 16.0.9
```
    "@gsa-sam/components": "16.0.9",
    "@gsa-sam/layout": "16.0.8",
    "@gsa-sam/layouts": "16.0.0",
    "@gsa-sam/ngx-uswds": "16.0.1",
    "@gsa-sam/ngx-uswds-icons": "16.0.0",
    "@gsa-sam/sam-formly": "16.0.9",
    "@gsa-sam/sam-material-extensions": "16.0.9",
    "@gsa-sam/sam-styles": "3.0.18",
    "@gsa-sam/shared": "16.0.8",
```

**Ticket Number**
IAEMOD-23522

**Additional context**
![IAEMOD-23522-clear-mark-issue-011024](https://github.com/GSA/sam-design-system/assets/117218338/809be480-a177-4f95-916a-4458de9c9d1c)

**Comment by yerramshilpa** [comment]
Issue is resolved in sam-formly@16.0.10
