### ISSUE TITLE
508 - sds-tabs component - div lacks role attribute

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1395]
**Components Involved**
sds-tabs

**Expected Behavior**
No 508 issues found with Access Assistant

**Actual Behavior**
Access Assistant has finding: "This DIV is focusable but lacks a role attribute." on `<div class="sds-tabs__content" tabindex="0">`

**Your Environment**
Angular 16.2.12
    "@gsa-sam/components": "16.0.10",
    "@gsa-sam/layout": "16.0.8",
    "@gsa-sam/layouts": "16.0.0",
    "@gsa-sam/ngx-uswds": "16.0.1",
    "@gsa-sam/ngx-uswds-icons": "16.0.0",
    "@gsa-sam/sam-formly": "16.0.10",
    "@gsa-sam/sam-material-extensions": "16.0.10",
    "@gsa-sam/sam-styles": "3.0.18",
    "@gsa-sam/shared": "16.0.8",

**Ticket Number**
IAEMOD-24435

**Additional context**

![image](https://github.com/GSA/sam-design-system/assets/75684861/38b396e7-afc0-4990-9f89-fe1954682b13)

Source code:
```
      <sds-tabs [(selectedTab)]="selectedTab">
        <sds-tab-panel #tab1 [tabHeader]="tab1Header">
          <ng-template #tab1Header>
            <span class="modules-tabs-header">Review</span>
          </ng-template>
          <app-module-entity-rel-display
            [model]="this.model"
            [displayType]="1"
          ></app-module-entity-rel-display>
        </sds-tab-panel>
        <sds-tab-panel #tab2 [tabHeader]="tab2Header">
          <ng-template #tab2Header>
            <span class="modules-tabs-header">Instructions</span>
          </ng-template>
          <app-module-entity-rel-instructions [stepStatusData]="props.stepStatusData"></app-module-entity-rel-instructions>
        </sds-tab-panel>
      </sds-tabs>
```

**Comment by yerramshilpa** [comment]
The issue resolved in @components@16.0.13 version
