### ISSUE TITLE
508 - Formly autocomplete loses focus

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1399]
**Components Involved**
Formly autocomplete

**Expected Behavior**
- When using the mouse to select a value in the autocomplete (single select) the focus should stay in the autocomplete field.
- When using the X or caret up buttons on the autocomplete the focus should return to the autocomplete field.

**Actual Behavior**
When using the mouse to select a value in the autocomplete (single select), or using the X button, or using the caret up button, the focus is lost.  When running JAWS, it will scroll the user to the top of the page instead of staying at the autocomplete field.

**Your Environment**
Angular 16.2.12
"@gsa-sam/components": "16.0.10",
"@gsa-sam/layout": "16.0.8",
"@gsa-sam/layouts": "16.0.0",
"@gsa-sam/ngx-uswds": "16.0.1",
"@gsa-sam/ngx-uswds-icons": "16.0.0",
"@gsa-sam/sam-formly": "16.0.10",
"@gsa-sam/sam-material-extensions": "16.0.10",
"@gsa-sam/sam-styles": "3.0.18",
"@gsa-sam/shared": "16.0.8",

**Ticket Number**
IAEMOD-24737

**Additional context**

**Starting out with field in focus:**
![image](https://github.com/GSA/sam-design-system/assets/75684861/efc4b8ae-75e3-4a20-8749-3028deeb041d)

**Using mouse to select a value, no focus:**
![image](https://github.com/GSA/sam-design-system/assets/75684861/e3fb8d1c-7c22-4a56-a0c7-8e48dab8c090)

**Clear/X button in focus:**
![image](https://github.com/GSA/sam-design-system/assets/75684861/d9fb1f41-dcbf-4495-8e3c-e1f7f870ae43)

**Press enter, loses focus:**
![image](https://github.com/GSA/sam-design-system/assets/75684861/fe3d5ee7-dfee-48dd-aa99-c26777c260f3)

**Caret up button in focus:**
![image](https://github.com/GSA/sam-design-system/assets/75684861/22b9814e-f749-4c42-876e-b8c41631e20a)

**Press enter, loses focus:**
![image](https://github.com/GSA/sam-design-system/assets/75684861/a60d30c5-d1f5-4229-8c4c-ac15d88825d2)

**Comment by yerramshilpa** [comment]
The issue resolved in @sam-formly@16.0.13 version
