### ISSUE TITLE
200% Magnification - Search Results Pagination Issue - Page number not shown

### ISSUE THREAD

**Issue by kisa-gsa** [GSA/sam-design-system#1449]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
@gsa-sam/components

**Expected Behavior**
How you expect the listed component(s) to function
At 200% magnification, the system accounts page should show the page numbers. Also, when you are not on the last page, the forward arrow should be disabled. 

**Actual Behavior**
How the listed component(s) actually function
Test System account MFE to 200% magnification for Web, Iphone SE and Ipad Air.
Search Results page number display is missing, and it is not showing as ”1 of X” for iPhone SE.
Also, the forward arrow button is not disabled when the user is on the last page. 

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
16.0.16

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.

IAEMOD-24489
**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

Steps to reproduce:

1. Login as System Account Administrator

2. In 200% magnification - observe the pagination of the search result.

Issue: If the search result has 27 pages, in 200% magnification, the pagination does not show the number of pages. Also, if user reaches 27th page (end of the test result), next button is not disabled and that kind of makes the user assume that there are further pages.

<img width="264" alt="Pagination Issue" src="https://github.com/GSA/sam-design-system/assets/144831918/6bb46bf6-a7e7-4380-931a-b13a2b52e67c">
<img width="734" alt="Behavior on 100%" src="https://github.com/GSA/sam-design-system/assets/144831918/275501b3-eb0f-42f6-ba33-e32bd8b615b9">

**Comment by cwolf10** [comment]
I've confirmed both issues are still present. I need to follow up with designers to confirm that "of X" is not meant to be hidden and that forward button should be disabled. Will update with responses.

**Comment by nishantg95** [comment]
Just wanted to add that this issue also exists in mobile view.

**Comment by cwolf10** [comment]
Not complete, need sam-styles release to complete.
