### ISSUE TITLE
508 Issue on input boxes, text not clearing with keyboard inputs

### ISSUE THREAD

**Issue by rithvik-mandalapu-gsa** [GSA/sam-design-system#1455]
**Components Involved**
Any component with an input box

**Expected Behavior**
Entering text and clicking tab to the clear button and hitting enter should clear any inputted text.

**Actual Behavior**
Occasionally the clear (x) button doesn't work using keyboard functions only. 

**Your Environment**
Angular Version: 16.2.12
@gsa-sam packages version: 16.0.16

**Ticket Number**
IAEMOD-24943 (2nd bullet point), note: as stated above this issue is not limited to this component alone.

**Additional context**
See JIRA Comments

**Comment by yerramshilpa** [comment]
@rithvik-mandalapu-gsa This issue is not reproducible. Not happening on the SDS demos
