### ISSUE TITLE
We are not able to vertically center the calendar icon.

### ISSUE THREAD

**Issue by VeeraRSareddy** [GSA/sam-design-system#1471]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with 

Date Picker  :  sds-formly-datepicker-range.  

**Expected Behavior**
We are not able to vertically center the calendar icon.

**Actual Behavior**
How the listed component(s) actually function:

Currently the calendar icon aligned to bottom instead center.

**Your Environment**
Angular Version: 17
@gsa-sam [packages]([url]([url](url))) version: X.Y.Z (Please list individually if all packages are not same version)

<img width="482" alt="image" src="https://github.com/GSA/sam-design-system/assets/84140857/f39e1619-a057-4d3f-af34-194d120fd308">

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-29900

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
@VeeraRSareddy Here is the link for the demo site where the icon is aligned centre, check your CSS if you are adding any CSS.

https://gsa.github.io/sam-design-system/?path=/story/formly-datepicker--basic
