### ISSUE TITLE
The component does not support changing the placeholder. 

### ISSUE THREAD

**Issue by VeeraRSareddy** [GSA/sam-design-system#1472]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-formly-datepicker-range

**Expected Behavior**
e.g. Should be removed from the placeholder or should give us the capability to change the place holder.

**Actual Behavior**
The component does not support changing the placeholder. Additionally, "e.g." should be removed from the placeholder

**Your Environment**
Angular Version: 17
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-29900

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

<img width="406" alt="image (1)" src="https://github.com/GSA/sam-design-system/assets/84140857/f4619c11-ddb5-4b83-ab12-27653ae1559d">

**Comment by yerramshilpa** [comment]
@VeeraRSareddy Component provides the feature to update the placeholder is working as expected, here is the demo where it's working, check your configuration on your end

http://localhost:6006/?path=/story/formly-datepicker--basic

**Comment by yerramshilpa** [comment]
The at is the default behaviour of the component.
