### ISSUE TITLE
To support horizontal table component 

### ISSUE THREAD

**Issue by NikhithaReddyG** [GSA/sam-design-system#1474]
**Is your feature request related to a problem? Please describe.**
To support the new feature need a horizontal table with following design.
![image](https://github.com/GSA/sam-design-system/assets/34350287/81e95dd5-e226-4db5-a790-4c36f021fc1e)

**Describe the desired solution**

**Describe alternatives you've considered**
Used grid row concept as alternative solution for now

**Additional context**

**Comment by cwolf10** [comment]
Hi @NikhithaReddyG, I was able to recreate this screenshot using our existing table component. Here is a screenshot of the demo I created: 
<img width="537" alt="image" src="https://github.com/GSA/sam-design-system/assets/72805180/11500de4-46d1-4731-bb3c-60235e069edd">

 and here is a [link](https://stackblitz.com/edit/angular-6fqt9f?file=src%2Fapp%2Ftable-basic.component.html) to that demo. Let me know if that works for you!

**Comment by NikhithaReddyG** [comment]
It's looking good now.

Thanks,
Nikhitha
