### ISSUE TITLE
55samfrontendcomp 508 Issue - content/supplychainorders TOU

### ISSUE THREAD

**Issue by P-Kondapalli** [GSA/sam-design-system#1475]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
@gsa-sam/components

**Expected Behavior**
How you expect the listed component(s) to function
While using AMP tool on the url i.e. https://55samfrontendcomp.apps.prod-iae.bsp.gsa.gov/content/supplychainorders, no error should pop-up stating "This element (role=dialog) does not have a mechanism that allows an accessible name value to be calculated". <div/> - SDS-DIALOG-CONTAINER

**Actual Behavior**
How the listed component(s) actually function
On AMP run on https://55samfrontendcomp.apps.prod-iae.bsp.gsa.gov/content/supplychainorders, there is a bug popped up i.e.
```This SDS-DIALOG-CONTAINER (role=dialog) does not have a mechanism that allows an accessible name value to be calculated```

**Your Environment**
Angular Version: 17.0.2 
(Please list individually if all packages are not same version)
@gsa-sam packages version: 
@gsa-sam/layouts- 17.0.2
@gsa-sam/layout- 17.0.2
@gsa-sam/shared- 17.0.2

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-22496

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

Steps to reproduce:

Visit the URL- https://55samfrontendcomp.apps.prod-iae.bsp.gsa.gov/content/supplychainorders
Select the "Download FASCSA Orders" button 
The "Terms Of Use" modal will display

In AMP Tool/ Access Assist Testing Procedure- There should not be an issue stating i.e. "This SDS-DIALOG-CONTAINER (role=dialog) does not have a mechanism that allows an accessible name value to be calculated" which is coming from sds-dialog-container  which is under overlay container that belongs to sam-design-system repo.

![image](https://github.com/GSA/sam-design-system/assets/164376647/205e446f-8e8e-42eb-b164-9e9a457f607a)
![image](https://github.com/GSA/sam-design-system/assets/164376647/84c3134f-8e57-4d79-86ef-dea425a6ed76)
![image](https://github.com/GSA/sam-design-system/assets/164376647/0d3347dc-6ee6-4509-8e06-6fd9ed4d1024)

**Comment by cwolf10** [comment]
The URL you linked does not work.

I just tested on our demo site for that component: https://gsa.github.io/sam-design-system/?path=/story/components-dialog--policy and am not seeing the error you are reporting.

I am guessing that this error has been resolve. If not, in order to address this issue I need to be able to reproduce this issue. Please provide a stackblitz example that I can see this error.

**Comment by P-Kondapalli** [comment]
Hi,

I Just tested the page URL from my end and it is working as expected, probably must have resolved later like you mentioned.  i.e.
![image](https://github.com/user-attachments/assets/da8d61f8-2bc7-4c78-b0d0-a2650c40d3f4)
![image](https://github.com/user-attachments/assets/17b393b4-e5cb-450a-a920-817d836f7e0b)

Thank you.
