### ISSUE TITLE
Update tooltip styling to match latest Design Team mockups

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1476]
**Is your feature request related to a problem? Please describe.**
The current **tooltip** styling does not match the tooltip styling used in the latest Entity Registration module Figma mockups.

**Describe the desired solution**
Updated styling of **tooltip** to match the latest Entity Registration module Figma mockups

**Describe alternatives you've considered**
I've implemented custom styles for now, but the border shape and position are not exactly matching.

**Additional context**

_Mockup tooltip styling:_
![image](https://github.com/GSA/sam-design-system/assets/75684861/47f74314-eb65-4037-940c-29033cf3211a)

**Comment by cwolf10** [comment]
This is resolved with the release of v17.0.7
