### ISSUE TITLE
Horizontal Filter - Allow 'Reset' to clear keyword input

### ISSUE THREAD

**Issue by yasminmenchaca** [GSA/sam-design-system#1477]
**Is your feature request related to a problem? Please describe.**
The keyword input on the Horizontal Filter does not clear with the user clicks 'Reset'. It will only clear the popover & date filter selections.

**Describe the desired solution**
Allow the user to clear the keyword input with 'Reset'.

**Describe alternatives you've considered**
The user can clear the input with 'X' for now.

**Additional context**

https://github.com/GSA/sam-design-system/assets/57374092/a9e1c1bd-b37c-48e3-842f-5f2e1094fd2b

**Comment by yerramshilpa** [comment]
This issue has been fixed updated SDS documentation for the implementation, there is not need to update any package version refer the implementation of the Horizontal demo 

https://gsa.github.io/sam-design-system/?path=/story/formly-filter--horizontal
