### ISSUE TITLE
SDS Table component enhancement

### ISSUE THREAD

**Issue by VeeraRSareddy** [GSA/sam-design-system#1484]
**Is your feature request related to a problem? Please describe.**

   According to the new mockup request, adding the multiple checkboxes and dropdown  in a data table results is not possible with SDS Table.  We are requesting to enhance the SDS Table component in order to satisfy the below requirement.

Please refer the below enabler request.
IAEMOD-29743

**Comment by cwolf10** [comment]
@VeeraRSareddy can you attach the mockup you are referring to?

**Comment by VeeraRSareddy** [comment]
<img width="1764" alt="image" src="https://github.com/GSA/sam-design-system/assets/84140857/5d57f0fd-6f57-459f-8837-f5acc09529c6">

**Comment by VeeraRSareddy** [comment]
@cwolf10 
Added the screen shot.  Its a Tier 2 page.

**Comment by cwolf10** [comment]
@VeeraRSareddy can you double check that screenshot? I don't see any checkboxes or dropdowns in that table.

**Comment by VeeraRSareddy** [comment]
@cwolf10  Yes we need to implement the check boxes as per this story IAEMOD-29743.  But right now the SDS Table component does not support the change.

Could you please reach Marcus for more info.
