### ISSUE TITLE
sds-pagination - Label issues

### ISSUE THREAD

**Issue by VeeraRSareddy** [GSA/sam-design-system#1485]
**Components Involved**
sds-pagination 

<img width="1728" alt="image" src="https://github.com/GSA/sam-design-system/assets/84140857/2341ea5a-f438-4373-9216-e4ceff05f13e">

**Expected Behavior**

1.  Current sds-pagination component does not show ('Page'). As per the mockups, please add the label 'Page'.
2.  Current sds-pagination component shows  ('Results per page'). As per the mockups, it should be ('results per page')
     Please refer the below screenshot.

<img width="1203" alt="image" src="https://github.com/GSA/sam-design-system/assets/84140857/0eb9d895-9999-4250-b680-d24757a485af">

**Actual Behavior**
<img width="1728" alt="image" src="https://github.com/GSA/sam-design-system/assets/84140857/0efe22d7-3f46-4045-9675-297f07a754fc">

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by cwolf10** [comment]
Issue looks good. This will get picked up as prioritization allows.

**Comment by cwolf10** [comment]
@VeeraRSareddy this is resolved in v17.0.13 of SDS.
