### ISSUE TITLE
Side Navigation with grey background for children content

### ISSUE THREAD

**Issue by NikhithaReddyG** [GSA/sam-design-system#1486]
**Is your feature request related to a problem? Please describe.**
This is feature request to support below design
![image](https://github.com/GSA/sam-design-system/assets/34350287/d9b0952e-77a9-46a2-a145-e4cb58876e5e)

**Describe the desired solution**

**Describe alternatives you've considered**
Used current sds side navigation component .

**Additional context**

**Comment by yerramshilpa** [comment]
@NikhithaReddyG  Can you attach the existing design how it looks

**Comment by NikhithaReddyG** [comment]
Here you go

![image](https://github.com/user-attachments/assets/9bab5dae-bb0c-4086-b2e7-e9e3fdcaf855)

**Comment by NikhithaReddyG** [comment]
![image](https://github.com/user-attachments/assets/49257730-483b-4e9a-a7dd-e31c75c29422)

**Comment by yerramshilpa** [comment]
Documentation added here is the link 
https://gsa.github.io/sam-design-system/pr-preview/pr-1501/?path=/story/components-side-navigation--selection
