### ISSUE TITLE
sds-table row color

### ISSUE THREAD

**Issue by BhardwajManasvi** [GSA/sam-design-system#1518]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/2c286a89-8fd3-4b7d-a016-9d3c9994f30f)
in one of the requirements we have to display the color in a row

**Describe the desired solution**
we should be able to apply the colors in the row

**Comment by cwolf10** [comment]
Hi Manasvi, per our conversation yesterday the table is applying your custom class as expected.

Config:
![image](https://github.com/user-attachments/assets/a7183313-c16e-41e0-917e-66ff31f036a5)
HTML:
![image](https://github.com/user-attachments/assets/c68ffa63-1781-410c-8f4b-72cffc940c95)


You just need to update that class to apply a background color to the td elements as we have done in the SDS demo. Here is the styling I am using in the demo:

![image](https://github.com/user-attachments/assets/7087066e-bbdc-4856-a7f7-c1ee39abc0b1)

And here is a link to our demo so you can see how it is being rendered out: https://gsa.github.io/sam-design-system/?path=/story/components-table--custom-classes

I am going to close this issue as the table is appending your custom class as expected, the styling for that class just needs to be updated to apply to the correct element.
