### ISSUE TITLE
New Buttons for Switching Between Card and List View in Modular Dashboard

### ISSUE THREAD

**Issue by shannoncates-gsa** [GSA/sam-design-system#1520]
In the modular dashboard, the user needs a way to toggle between the card view and the list view.

We have designed buttons for this, and they need to be added to our components.
There is a Figma file available to view upon request.

![toggle buttons](https://github.com/user-attachments/assets/136eb1d7-e227-4137-ae9a-72dae542da57)

**Comment by brandydanner-gsa** [comment]
The buttons are working correctly for me, thank you!  But do you know why I'm getting this console error when the page loads?

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/d4013883-0374-49a5-8bea-4dcc158d6530">

**Comment by cwolf10** [comment]
I just checked our demo page for that new mode to see if the error was showing up there and I am not seeing any being thrown on that page. So I'm not sure what's causing that error to show up.

**Comment by brandydanner-gsa** [comment]
@cwolf10  I'm also seeing the error when running the unit tests and it's failing the tests:

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/b0acfb19-50a3-43e1-a2f7-b373bbcc0a67">

**Comment by brandydanner-gsa** [comment]
If it helps, this is the line of code referenced in the stacktrace above for sam-material-extensions
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/5747e4ad-a9c4-4801-868e-160bf19c48d3">

It seems to corresponds to this code? https://github.com/GSA/sam-design-system/blob/master/libs/packages/sam-material-extensions/src/lib/button-group/button-group.component.html#L19

**Comment by cwolf10** [comment]
@brandydanner-gsa can you message me with the HTML you're using for the button group on that page? Maybe you've got something extra going on that our demo doesn't.
