### ISSUE TITLE
New Color Options for Table Header

### ISSUE THREAD

**Issue by shannoncates-gsa** [GSA/sam-design-system#1521]
In the modular dashboard, we are using different colors for the table header in the list view. 
We need to add the option for devs to use those colors with our current table header component.

The colors needed:
info-lighter: #E7F6F8 
accent-cool-light: #D9E8F6 
primary-lighter: #E3F5E1 

Figma file available to view upon request.

![image](https://github.com/user-attachments/assets/a919ce0e-db3c-4a3f-80cf-3ea75ec83941)

**Comment by cwolf10** [comment]
@shannoncates-gsa these have been added in v17.0.13 of SDS. Here's a link to the demo: https://gsa.github.io/sam-design-system/?path=/story/components-table--header-color
