### ISSUE TITLE
New Colored Buttons for Modular Dashboard

### ISSUE THREAD

**Issue by shannoncates-gsa** [GSA/sam-design-system#1522]
There are a couple of new buttons we are using in the modular dashboard.

We need buttons in the following colors:

info-light: #9DDFEB (This will be our in progress button color)
error-lighter: #FDB8AE (This will be our error state button)

Other states are shown in the attached screenshot. Figma available upon request.

<img width="925" alt="Screenshot 2024-09-06 at 12 29 47 PM" src="https://github.com/user-attachments/assets/94998b4b-d557-4023-8501-ddc8db559b2c">

**Comment by cwolf10** [comment]
@shannoncates-gsa these have been added in v3.0.23 of sam-styles. Here's a link to the demo: https://gsa.github.io/sam-styles/?path=/story/components-button-standard--variants
