### ISSUE TITLE
Date Range picker is not 508 JAWS compliance

### ISSUE THREAD

**Issue by RakeshReddy-REISys** [GSA/sam-design-system#1540]
**Components Involved**
Date Range Picker

Here are the test results on the updated Date Range picker and also the feedback that we have received from Dan Perkins for the Date range picker that we use in Date bank reports.

Issue observed by Reporting team on Updated  Date Range Picker:
Jaws is not reading the place holder correctly
Jaws is not reading the expected date format
Validation message is not reading by Jaws
Jaws is not reading if the date is selected 

Testing results:  https://drive.google.com/file/d/1vdqJPZMsfwBrfXpW38mOPYTj22XC_GiM/view?usp=sharing
Issue observed by Dan Perkins for Data bank Date Range picker(sam-ui-elements):
Automatically changes Focus on to next field 
Intermittently Jaws reading the values of previous date field 
Testing session records conducted by Dan perkins 
https://drive.google.com/file/d/17BiZmiVZC_icWHpllQd_WF19aVe2mOhb/view

I suggest scheduling a working session with Dan Perkins to go over the updated Date range picker. This will help ensure that everyone involved has a clear understanding of what the expected outcome should be.

**Comment by RakeshReddy-REISys** [comment]
Date Range Picker that we use in Sam.gov is having with issue while testing with JAWS. 
This has been discussed in FWG meetings on 9/25/2025 and we do have an email chain for this issue

**Comment by yerramshilpa** [comment]
@RakeshReddy-REISys The JAWS issue is resolved in @gsa-sam/sam-formly@17.0.12 version
