### ISSUE TITLE
Radio button border width not matching

### ISSUE THREAD

**Issue by Nysharma** [GSA/sam-design-system#1552]
**Components Involved**
Radio Button

**Expected Behavior**

**Actual Behavior**
How the listed component(s) actually function

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
@Nysharma I am currently working on this

**Comment by yerramshilpa** [comment]
The issue was resolved in sam-styles@3.0.21 version
