### ISSUE TITLE
FSRS: Tier 3 - SideNav of Subaward Details (Mobile/tablet view)

### ISSUE THREAD

**Issue by VeeraRSareddy** [GSA/sam-design-system#1553]
**Is your feature request related to a problem? Please describe.**
The current side navigation does not support adaptive views. Please find attached screenshots of the current behavior and the expected behavior.

**Current Behaviour**
<img width="669" alt="image" src="https://github.com/user-attachments/assets/99e47f7c-7bc5-47cd-bd99-1e23ef34cf7c">

<img width="481" alt="image" src="https://github.com/user-attachments/assets/e4f3fecf-fd4d-4f99-bde9-595523f75784">

**Expected Behaviour**

<img width="478" alt="image" src="https://github.com/user-attachments/assets/a00c2ce6-3b76-4fb8-8da0-f14d684544bc">

**Describe the desired solution**
Please enhance the recommended side navigation to use the desktop view for better support of the expected behavior on mobile and tablet views. The current behavior does not adapt to tablet and mobile resolutions.
For more information, please refer to the mockup in Figma, specifically the side navigation on the Subaward Details page. (You can access this page through the side navigation of the provided Figma link.)

https://www.figma.com/proto/yPractYdoD71MevcbBTxgF/FSRS-Data-Entry_PI49?node-id=33349-24994&node-type=frame&t=xbeGaBbkKqDCqG4N-0&scaling=min-zoom&content-scaling=fixed&page-id=30231%3A17733&starting-point-node-id=33349%3A24847&show-proto-sidebar=1

**Comment by yerramshilpa** [comment]
This feature is already available in the existing component, Here are the properties you need to use. Here is the demo for the above feature

https://gsa.github.io/sam-design-system/?path=/story/components-side-navigation--filters

 [responsiveButtonText]="'Advanced Search'"
    [responsiveButtonIcon]="'chevron-left'"
    [responsiveSize]="1000"
