### ISSUE TITLE
When user clicks 'Custom date' 2 new filters appear 'To' and 'From' => should not trigger a getData search

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#306]
I would like to look at the possibility of not calling getData() when a new filter is revealed, yet data has not yet been inputed.  Can this be handled by formly or should we construct a full date model at all times so that hiding and revealing will not show as a 'model change' ?  We are also looking into ways that getData() would not be called until filterModel is fully constructed on page load, possibly with a router resolver?

![image](https://user-images.githubusercontent.com/58823468/88690322-637a4380-d0b0-11ea-9410-aa26f9e66428.png)

**Comment by Bibek-Regmi** [comment]
Deprecated issue - applications have input options to control whether getData is called or not. In addition, @gsa-sam/layouts is no longer supported through this SDS repo
