### ISSUE TITLE
'more filters' update 6.22

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#316]
![image](https://user-images.githubusercontent.com/58823468/89835940-942f9380-db1a-11ea-899b-8105f71c3377.png)

When I click 'Contract Award Details' => 1) first 2 fields show 2) Title shows 3) Contract Award Details toggles

Expected behavior all 4 sub links are selected when I click top level header.

**Comment by yerramshilpa** [comment]
The issue is with the older version of ngx-formly core. Updating the version to ngx-formly/core to 5.10.1 is fixed the issue.
