### ISSUE TITLE
"Reset All" from the Side Navigation component is not clearing the UI for single selects

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#330]
When the autocomplete filter Selection mode is single select the Reset All function is not clearing the UI text box from the selected item.

**Using the filter**
![InkedWD_MFE_Reset_All_LI](https://user-images.githubusercontent.com/66032295/91329667-6bec9980-e796-11ea-919d-b0ccf9eb91bf.jpg)
**After Reset All**
![InkedWD_MFE_Reset_All_Defect_LI](https://user-images.githubusercontent.com/66032295/91329712-7b6be280-e796-11ea-8ded-be4ebedb12ac.jpg)

**Comment by yerramshilpa** [comment]
The issue is resolved in @gsa-sam/sam-formly@0.6.28 version
