### ISSUE TITLE
Autocomplete with hide, does not clear child value in UI - wage determination state and counties filters

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#339]
in our state and counties filter when user clicks clear on state counties filter is hidden
when user clicks another state old county value returns even tho model is cleared.
this fix needs to be applied by design as changes on our side do not affect the html display of filters
may be an issue with nested for loops as both state and counties are arrays

https://stackoverflow.com/questions/40663198/ng-reflect-model-shows-correct-value-but-not-reflecting-in-input may point to a solution for the form

**Comment by yerramshilpa** [comment]
Here is the documentation for on hideExpression changes  with clear UI, here is the link.

https://github.com/GSA/sam-design-system/tree/master/libs/documentation/src/lib/components/filters/demos/hideexpression
