### ISSUE TITLE
Downloads Dialog download button is enabled even when file name is empty

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#341]
There should be some logic to only enable the downloads button once all required information is entered by the user.
In this scenario the file name is required and the downloads button is enabled even when there's no input by the user.

![image](https://user-images.githubusercontent.com/66032295/92263605-e1e5b480-eeaa-11ea-94e0-809dea1f6aec.png)

**Comment by yerramshilpa** [comment]
The validations added to the dialog model in the @gsa-sam/sam-formly@0.6.26 version. Here is the documentation for the implementation.
https://github.com/GSA/sam-design-system/tree/master/libs/documentation/src/lib/components/download/demos/download
