### ISSUE TITLE
Tooltip/Popup Starting and Staying Open

### ISSUE THREAD

**Issue by bkmurray** [GSA/sam-design-system#359]
After importing the required SdsPopupModule to a page, the Popup starts open on page load and stays open. It is also behind other text on the page. The strange thing is it was working correctly on another page in the same project.
![image](https://user-images.githubusercontent.com/18359224/93527699-3f481f80-f907-11ea-9fb2-16a4a4eda386.png)

**Comment by yerramshilpa** [comment]
This is fixed in 10.0.10 version
