### ISSUE TITLE
Formly Button

### ISSUE THREAD

**Issue by ascreven-gsa** [GSA/sam-design-system#379]
Sam Formly button type should have option to add classes such as `usa-button usa-button--secondary`. If unstyled is the most used button type this could possibly be the default if classes are not passed.

**Comment by davereed** [comment]
The button type is currently used only for an internal implementation. Is there a requirement for a button type you can point us to so that we can evaluate the need and priority?

**Comment by ascreven-gsa** [comment]
The CFDA Download card on the Assistance Listings landing page

**Comment by davereed** [comment]
In that use case, it would be better to have the download button be the submit button, which lives outside of the formly fields and is within your control to style as you wish.

![image](https://user-images.githubusercontent.com/1132092/95137780-d64e0d80-0736-11eb-8abe-f0787ea766c5.png)

I agree when we decide to expose the button type it should be more flexible, but I can't recommend using it for the landing page.
