### ISSUE TITLE
MultiSelect component data type inconsistency 

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#383]
Can the multiselect data type for the checkboxes be either all boolean or all string. 
I found that when setting "defaultValue" in the formly config these values are set as string but when the user interacts with the checkbox the values become of type boolean. This is causing a bug already with the component "select all" option in this case you can see in the image below that "All Domains" is unchecked as if all the children were unchecked however fh and wd are still checked because of the default setup. For the other 3 unchecked domains I manually clicked on them to remove the check.

![image](https://user-images.githubusercontent.com/66032295/95783545-16197580-0ca0-11eb-8be2-4b3b9f4f0ee6.png)
![image](https://user-images.githubusercontent.com/66032295/95783657-4f51e580-0ca0-11eb-8249-1c6eb36712e0.png)
![image](https://user-images.githubusercontent.com/66032295/95782982-eb7aed00-0c9e-11eb-96c4-ac603c613393.png)

**Comment by yerramshilpa** [comment]
This issue is not a component issue, here is the demo for the Multicheckbox 

https://github.com/GSA/sam-design-system/tree/master/libs/documentation/src/lib/components/formly/multicheckbox/demos/selectall
