### ISSUE TITLE
Filters with disable expression not updating in the UI when loading a history url

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#387]
Filter STATE has a disabled filter COUNTY and these do not re-inflate when the history url is loaded

**Comment by yerramshilpa** [comment]
@jesseboydgsa  There were some changes related to this issue in @gsa-sam/sam-formly@0.6.28 version, Can you check and confirm if the issue still exist.

**Comment by yerramshilpa** [comment]
The issue resolved in @gsa-sam/sam-formly@0.7.2 version
