### ISSUE TITLE
First interaction with sds-toolbar (e.g selecting a Domain) is resetting formly filterModel 

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#393]
In Search MFE when I first load the application and land at the 'All Domains' search results if I enter a keyword, or any other filter that I want to preserve, when I change domains the filterModel is reset so the filter data is lost. The ngOnInit method is being called with that first domain switch.
This only happens on initial domain switch, afterwards no filterModel reset or ngOnInit execution happens.
The use case is preserving the keyword term across domain switch.

Below a sc of the filterModel as we switch from 'All Domains' to 'Opportunities' after initially loading the page and search for the keyword "hello" in 'All Domains'
![image](https://user-images.githubusercontent.com/66032295/97230154-d1b5cb80-17af-11eb-92fd-6b5f6acb5126.png)

**Comment by yerramshilpa** [comment]
The issue has been resolved to change the data type of filterChange$ on your application to Subject
