### ISSUE TITLE
Search URL

### ISSUE THREAD

**Issue by ascreven-gsa** [GSA/sam-design-system#397]
Add an optional url parameter to search for routing until MFEs are integrated by using an `a` tag with passed in base href. Currently, unless there's a better way I'm unaware of (if so, please include a demo), to route to search from another MFE a function has subscribe to modelChanges for click event, check if form is valid and then call window.location.href causing a complete page refresh to get to another MFE page.

**Comment by Bibek-Regmi** [comment]
@ascreven-gsa - We want to try and avoid taking on routing responsibilities as much as possible as a component library. The responsibility of managing route changes should fall at an application or sam-ui-common level. The responsibility of search from Sam Design System should stay at just notifying its clients of change and avoid acting on the changes.
