### ISSUE TITLE
Search Model

### ISSUE THREAD

**Issue by ascreven-gsa** [GSA/sam-design-system#401]
User is able to submit search before text in entered in search bar even when the field is required, thus disabling the entire form. However, we cannot observe changes to the search field until the form has been submitted. This is causing issues on the search bars on landing pages since we need to route to the Search MFE using search input and value from "show Active only" checkbox. Therefore, we cannot simply watch for model changes and reset the form if text is not entered.

**Comment by yerramshilpa** [comment]
Duplicate issue https://github.com/GSA/sam-design-system/issues/458
