### ISSUE TITLE
sds header and button group flex issue

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#409]
no matter where I put the sds-button-group it always is on the left side and not on the right as intended

here you can see i have placed sds-button-group as the last item within sds-header and yet no matter what I try it shows up on the left
![image](https://user-images.githubusercontent.com/58823468/98734736-3ef06180-2357-11eb-9837-cfe7a3e4ae07.png)

by unselecting display flex i am finally able to see the button group move to the right, may or may not be the fix
![image](https://user-images.githubusercontent.com/58823468/98734545-f173f480-2356-11eb-80c4-e86e56a7506a.png)

also note the bad vertical alignment in design prototype
![image](https://user-images.githubusercontent.com/58823468/98734687-2ed88200-2357-11eb-9f7e-aabdba7ecc1f.png)

**Comment by KidanyGSA** [comment]
This was fixed with the 0.71 release

**Comment by Bibek-Regmi** [comment]
Closing as fix seems to have been released with version 0.7.1
