### ISSUE TITLE
SdsFiltersComponent forces import of DatePipe service

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#410]
SdsFiltersComponent  something is wrong in the way this class imports DatePipe or it's module handles DatePipe as I have to import in my app.module -> provider 'DatePipe' for the error to go away.  Packaging issue i suspect.

![image](https://user-images.githubusercontent.com/58823468/98877740-0bd0cf80-2436-11eb-9a30-2ce9423806b0.png)

**Comment by jesseboydgsa** [comment]
![image](https://user-images.githubusercontent.com/58823468/99597312-a8eab580-29ac-11eb-9d75-904813d1e993.png)
work-around

**Comment by yerramshilpa** [comment]
Issue resolved in @gsa-sam/sam-formly @0.7.1 version.
