### ISSUE TITLE
Sds single select Autocomplete not clearing input on clear button clicked

### ISSUE THREAD

**Issue by Bibek-Regmi** [GSA/sam-design-system#411]
on single select mode, with free text disabled, if a user selects an item from autocomplete, they are not able to clear it by clicking on the (x) button in the input field. The recording shown is from deployed master branch as of time of this comment

[Screen Recording 2020-11-13 at 1.03.20 PM.mov.zip](https://github.com/GSA/sam-design-system/files/5538567/Screen.Recording.2020-11-13.at.1.03.20.PM.mov.zip)

**Comment by jesseboydgsa** [comment]
this appears to be related to my issue #417 also

**Comment by Bibek-Regmi** [comment]
Closing as duplicate to #417
