### ISSUE TITLE
Autocomplete with SelectionMode.SINGLE can't close using 'x'

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#417]
![image](https://user-images.githubusercontent.com/58823468/99683050-c5323500-2a34-11eb-9716-04f09034bc42.png)
clicking the 'x' has no response in the application nor any errors or warnings.  does work with SelectionMode.MULTIPLE used elsewhere.   

Please consider using the S.O.L.I.D principles and not smash many types of filters inside an autocomplete.  Will make isolation and debugging much easier.

currently using @gsa-sam/components 0.7.0 with app at ng 8

**Comment by yerramshilpa** [comment]
The issue resolved in sam-components@0.7.2 version
