### ISSUE TITLE
Accordions are not displaying properly after MFE Search Angular upgrade to 10

### ISSUE THREAD

**Issue by puspendupalgsa** [GSA/sam-design-system#421]
After the angular upgrade, we are seeing 2 major issues. 
1) The accordions are not displaying properly. Screenshot attached here.
2) The linkEvent in sds side navigation component is not triggering. (https://github.com/GSA/sam-design-system/issues/414)

![image](https://user-images.githubusercontent.com/66069671/99848660-2b5bac80-2b48-11eb-8556-5a58855442e1.png)

**Comment by yerramshilpa** [comment]
Issue resolved in @gsa-sam/sam-formly@10.0.0-beta.4 version
