### ISSUE TITLE
re-occurring issue with getData called multiple times when it should only be called once

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#428]
we have faced this issue many times.  i believe the best approach is for us to provide a behaviorSubject or some type of subject and control when next is emitted.   otherwise we will continue to battle with getData called multiple times making multiple api calls with very little control or even know exactly when or why it is called.

**Comment by yerramshilpa** [comment]
@jesseboydgsa  Can you confirm, is this issue still exist.

**Comment by jesseboydgsa** [comment]
hi Shilpa i still see 2 api calls on some domains when using side navigation but page load looks good with just 1x api call

**Comment by yerramshilpa** [comment]
@jesseboydgsa Then I feel this is definitely from your end. I will be closing as this works on page load.
