### ISSUE TITLE
search bar issue with mobile view

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#432]
When switching to mobile view and clicking on search (magnifying glass icon) the searchbar overlaps the back button. When switching back to desktop view the searchbar doesn't go back to the original position.
![image](https://user-images.githubusercontent.com/66032295/100480737-20f95f80-30c0-11eb-95ff-3a8aae970d37.png)
![image](https://user-images.githubusercontent.com/66032295/100480861-72a1ea00-30c0-11eb-875c-86f3f0d75ff0.png)

![image](https://user-images.githubusercontent.com/66032295/100480831-61f17400-30c0-11eb-85ba-0e485a9c8518.png)

**Comment by cwolf10** [comment]
@KidanyGSA this should have been resolved with release 0.72. Can you confirm the issue is resolved?

**Comment by KidanyGSA** [comment]
I can confirm that is not an issue anymore.
