### ISSUE TITLE
Reset ALL is ignoring the default values of filter config (Status filter) 

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#441]
Reset ALL shouldn't uncheck "Active" as it is true by default. It used to work fine up to at least PI 27 which is the version in alpha. 
![image](https://user-images.githubusercontent.com/66032295/100922954-7eb8ed80-34ac-11eb-8663-eef5c29c93bc.png)

![image](https://user-images.githubusercontent.com/66032295/100922881-63e67900-34ac-11eb-8652-1fac3dbc2ac1.png)

**Comment by Bibek-Regmi** [comment]
Setting the default value on the model rather than through formly should give you the behavior you're looking from - https://formly.dev/examples/field-options/default-value

**Comment by Bibek-Regmi** [comment]
Closing as defining initial value on model resolves the issue
