### ISSUE TITLE
Agency picker overflowing URL history

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#450]
steps to reproduce: pick an agency from the agency picker.  Parul has contacted Hunter Green as their model contains a huge blob of information when only key and value are needed.  This is most likely an issue for Hunter Green but I'm posting this for awareness.  it may take up to 3 or 4 agencies for this error to manifest.

![image](https://user-images.githubusercontent.com/58823468/101214727-50b0e600-3631-11eb-9a2a-025b4ac459b9.png)

**Comment by yerramshilpa** [comment]
@jesseboydgsa  can you try with gsa-sam-shared-10.0.5-beta.0 version and let me know if this still exists.

**Comment by yerramshilpa** [comment]
Issue resolved in gsa-sam-shared-10.0.5-beta.0
