### ISSUE TITLE
Angular 10 Upgrade - Entity MFE - Duplicate labels on formly filters when importing SharedFormlyModule

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#453]
In the module file on one of the sam-frontend-entity workspaces, SharedFormlyModule is imported along with SdsAgencyPickersModule from @gsa-sam/shared@10.0.1.  The SharedFormlyModule is causing duplicate labels on the formly filters.  Removing this import fixes the filter labels, however it cannot be removed permanently since the Agency Picker requires it.

[exclusion-workspace.module.ts.txt](https://github.com/GSA/sam-design-system/files/5660124/exclusion-workspace.module.ts.txt)

Duplicate labels when SharedFormlyModule is imported:
![Duplicate_Labels](https://user-images.githubusercontent.com/75684861/101503612-4566fe80-3940-11eb-9bde-e7a1742cacdd.PNG)

When SharedFormlyModule is commented out:
![Correct_Labels](https://user-images.githubusercontent.com/75684861/101503633-4a2bb280-3940-11eb-9fad-847947c16f58.PNG)

Package version from package.json:
   "@gsa-sam/components": "^10.0.0-beta.3",
    "@gsa-sam/layout": "^10.0.1",
    "@gsa-sam/layouts": "^10.0.0-beta.3",
    "@gsa-sam/sam-formly": "^10.0.0-beta.3",
    "@gsa-sam/sam-material-extensions": "^10.0.0-beta.3",
    "@gsa-sam/sam-styles": "0.0.89",
    "@gsa-sam/shared": "10.0.1",

**Comment by yerramshilpa** [comment]
Duplicate issue [421](https://github.com/GSA/sam-design-system/issues/453)
