### ISSUE TITLE
Sds Action Button - model appears to be global

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#457]
Usage as a single button there are no issues, even when dynamically changing the model to have different options.

The problem appears when loading many rows each containing an action button.  It appears that the 'menu' might be held globally even though each row is given a new instance of a 'menu' object.

![image](https://user-images.githubusercontent.com/58823468/101681930-c1804580-3a17-11eb-9c8d-fcd751489f78.png)

when I click the action button '...' not a submenu, the click method is called, this is not intended and should only be called when i click on a menu item within the action.  on this clicking of the '...' our click method is called for every single row.

![image](https://user-images.githubusercontent.com/58823468/101681799-9564c480-3a17-11eb-8f8f-46637b8e1d62.png)

For some reason when I click anywhere in the row, getTableRowMenu() is called and it is called for every single row element on the page.  Expected behavior:  clicking anywhere in row, no action, getTableRowMenu() getting 1 time for each row and only once on page load to supply the menu.

**Comment by jesseboydgsa** [comment]
The following video show just how many times our action menu is called, when loading the page, when clicking anywhere on a row and when clicking the '...'
[actionsCalledWhenClickingRow.zip](https://github.com/GSA/sam-design-system/files/5669453/actionsCalledWhenClickingRow.zip)

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa Making method calls in templates is generally not a good practice - https://medium.com/showpad-engineering/why-you-should-never-use-function-calls-in-angular-template-expressions-e1a50f9c0496.

You can use pure pipes or pre-set the actions / manually update when your data changes. Here's a small demo on stackblitz - https://stackblitz.com/edit/angular-scss-demo-xwpnmj?file=src%2Fapp%2Fapp.component.ts
