### ISSUE TITLE
Demo Code Snippets 

### ISSUE THREAD

**Issue by ascreven-gsa** [GSA/sam-design-system#469]
Source Code and Template Markup in component demos are not displaying on Federalist:
<img width="1141" alt="Screen Shot 2020-12-29 at 2 50 57 PM" src="https://user-images.githubusercontent.com/11817992/103310404-c57b0400-49d4-11eb-8ed1-82286c3f0f95.png">

**Comment by Bibek-Regmi** [comment]
Resolved
