### ISSUE TITLE
Saved searches on load, does not display filter components (with values) , which are not visible by default

### ISSUE THREAD

**Issue by puspendupalgsa** [GSA/sam-design-system#477]
Create a saved search with filters from More Filters section, which are not initially visible. Save the filters and load them back again. The saved search results are loaded correctly, but the components  which are part of "More Filters" and not visible initially are not displayed.

If you select those components back again from More Filters you can see the filter values populated.

To recreate the issue:
See screenshot attached.
Go to Opportunities domain and create saved search   with Awarded Amount and Award Number.
Save the saved search.
Log out
Log back in
go to your saved search list page
Click on the saved search link to load the saved search.

![image](https://user-images.githubusercontent.com/66069671/103375159-72be4c80-4aa7-11eb-8ebf-f951876e011a.png)

**Comment by Bibek-Regmi** [comment]
Resolved as of 10.0.5
