### ISSUE TITLE
SdsAutoComplete component model undefined error

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#478]
`this.model is undefined `when loading a saved search, for the first time in a while i am seeing all the chips render correctly but now I have this issue.  I believe that since we are injecting values into an autocomplete and not calling the service perhaps the model is not provided yet.  can we add a null guard?  this error is preventing the results from loading.  

![image](https://user-images.githubusercontent.com/58823468/103386607-90de7980-4ab4-11eb-9243-459cb098b674.png)

![image](https://user-images.githubusercontent.com/58823468/103386633-af447500-4ab4-11eb-95c2-6b0cff940ef5.png)

if i run resultlist.updateFilter(filterModel) this will update the results but remove the chips.  if i don't run this i get the chips but the results are never updated.  @yerramshilpa by commenting this line i also see the index url, if i add it back there is no index.
![image](https://user-images.githubusercontent.com/58823468/103387354-11eb4000-4ab8-11eb-9b03-d1346b368edd.png)

@Bibek-Regmi

**Comment by Bibek-Regmi** [comment]
Resolved in the mentioned pull request
