### ISSUE TITLE
HistoryUrl unaffected by any attempts to delete or change a url param

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#480]
logging any url changes and clearing the URL
![image](https://user-images.githubusercontent.com/58823468/103427725-94870480-4b77-11eb-85be-4c102340334c.png)

as you can see even when i try to clear the url it is holding state.  after reading the preference_id i wish to remove it from the url.
after changing domains i wish to clear the historyurl but it still contains the history from the previous domain.
![image](https://user-images.githubusercontent.com/58823468/103427738-a2d52080-4b77-11eb-94dc-0a0db4480f89.png)

Our router.navigate methods to modify the url worked before but have NO affect now

**Comment by ascreven-gsa** [comment]
This is also causing issues when routing to search from content since the search parameters the user entered are deleted.

**Comment by jesseboydgsa** [comment]
Thanks to design updates and moving our fields to ngOninit lifecycle and removing ngIfs from our page template this issue appears to be resolved.
