### ISSUE TITLE
History URL is not working on refresh/bookmarking

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#499]
**Components Involved**
sds-results

**Expected Behavior**
When refreshing the Search page I should get the same results as I had. The url params/filters should not be reset

**Actual Behavior**
The history url resets the values to default losing all selected filters

**Your Environment**
Angular Version: 10
@gsa-sam packages version: 10.0.4

**Comment by Bibek-Regmi** [comment]
Should be resolved as of 10.0.5. Filters kept on reload when history is enabled - stackblitz example here - https://stackblitz.com/edit/angular-gcf63x?file=src%2Fapp%2Fsidenavigation-optional.component.ts
