### ISSUE TITLE
Switching Domains does not add "index" param to the URL anymore

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#500]
**Components Involved**
SDS-toolbar

**Expected Behavior**
I expect to see the index in the url and that the index value update whenever a domain is selected from the toolbar

**Actual Behavior**
There's no index param even when trying to manually add it, the history will remove it.

**Your Environment**
Angular Version: 10
@gsa-sam packages version: 10.0.4

**Additional context**
![image](https://user-images.githubusercontent.com/66032295/104610245-e50b6100-5651-11eb-813e-6b678b4ede10.png)

**Comment by KidanyGSA** [comment]
Even in the Design prototype with the new navigation toolbar the issue can be replicated... 
In this case there is an index when switching from domains but as soon as the History kicks in, the index is removed from the url.
[https://federalist-e1ade7fb-52e9-46c3-b273-1ab1fd05e2fa.app.cloud.gov/site/gsa/sam-prototypes/#/search?index=opportunities](url)

**Comment by Bibek-Regmi** [comment]
Should be resolved as of 10.0.5. Stackblitz example here - https://stackblitz.com/edit/angular-gcf63x?file=src%2Fapp%2Fsidenavigation-optional.component.ts
