### ISSUE TITLE
more filters - inactive filter toggle - reset all does not clear

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#519]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-filters

**Expected Behavior**
How you expect the listed component(s) to function
i expect when i click reset all that the 'inactive filter toggle' will reset to unchecked

**Actual Behavior**
How the listed component(s) actually function
when i click reset all, the inactive filter toggle is unaffected

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
ng10
gsa-sam 10.0.5

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/58823468/105779493-59cc7e00-5f23-11eb-8cfe-c08d4ab89fa4.png)

**Comment by Bibek-Regmi** [comment]
No longer an issue as of 10.0.6
