### ISSUE TITLE
Datepicker Use Within sds-filters 

### ISSUE THREAD

**Issue by bkmurray** [GSA/sam-design-system#536]
The Datepicker component has 2 issues when trying to use it as a filter:

1. The change function on the TemplateOptions provided to the filter is not being triggered when a date is chosen from the calendar part of the Datepicker.
2. When deleting the info in the input box of the Datepicker, once you get past the day (ex. the 29 in Jan 29, 2021) the accordion closes, the Datepicker blocks the accordion and the accordion can only be reopened if you choose another date using the calendar, as shown below. This doesn't happen if you highlight the entire contents of the input box and delete it all at once, and I have seen times where the Datepicker doesn't overlap at all.
![image](https://user-images.githubusercontent.com/18359224/106323553-97901600-6245-11eb-9abb-32b6baa20da4.png)

**Comment by Bibek-Regmi** [comment]
@bkmurray Should be resolved in 10.0.10 relese

**Comment by bkmurray** [comment]
The change function is now firing for the Datepicker, however the accordion is still closing on partial info deletion, though the Datepicker is not still covering the accordion. After talking with Bibek, and looking at an example on Stackblitz, we realized that the fix Bibek put in was for the 'group' version of the accordion and not the 'wrapper' one that our team is using for the filters. He said that the fix will be applied on the 10.0.11 release

**Comment by Bibek-Regmi** [comment]
Resolved as of SDS package versions 10.0.11
