### ISSUE TITLE
White column under toolbar component present after sam styles v 0.0.94

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#538]
**Components Involved**
sds-toolbar

**Expected Behavior**
No white column, just the toolbar as it was before.

**Actual Behavior**
Extended white column under toolbar component

@gsa-sam packages version: 10.0.8 
sam-styles version:  0.0.98

![image](https://user-images.githubusercontent.com/66032295/106477354-11a6e180-6476-11eb-89ef-8e548a44ade6.png)

**Comment by yerramshilpa** [comment]
@KidanyGSA , we are working on this issue it will be part of our next releases

**Comment by KidanyGSA** [comment]
ok thanks!

**Comment by yerramshilpa** [comment]
This has been resolved with the new implementation and  SDS packages 10.0.9 version and sam-styles@ 0.0.99  version
