### ISSUE TITLE
History - Custom date values  do not stick when the history URL is refreshed.

### ISSUE THREAD

**Issue by puspendupalgsa** [GSA/sam-design-system#540]
**Components Involved**
History functionality using Sds Filters (Date Component - Custom Date option)

**Expected Behavior**
.The custom date option's value should stick after the URL refresh. 

**Actual Behavior**
After selecting custom date option and value  and refreshing the URL, the custom date value is lost and the results count do not match to what was there on the page before refresh

**Your Environment**
@gsa-sam packages version: 10.0.8
sam-styles version: 0.0.94

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/66069671/106490895-4cb01180-6484-11eb-93d7-df74938377cf.png)

**Comment by jesseboydgsa** [comment]
Probably because of the nesting of the formly filter.  Example filterModel for published date with just from chosen

` {publishedDate : { publishedDateSelect: "customDate", publishedDateFrom: "2021-01-28TO8:00:00:00.000Z } }`

**Comment by Bibek-Regmi** [comment]
Please reproduce your scenario on stackblitz - I've created a small example that seems to behave as expected - https://stackblitz.com/edit/angular-gcf63x-fo4q6r

**Comment by puspendupalgsa** [comment]
Reproduced the scenario on stackblitz @ https://stackblitz.com/edit/angular-gcf63x-wpblfv

**Comment by puspendupalgsa** [comment]
![image](https://user-images.githubusercontent.com/66069671/107255517-62828100-6a06-11eb-9a68-f0ddf0373aab.png)

Added "hideExpression"

**Comment by Bibek-Regmi** [comment]
@puspendupalgsa - Thank you - This issue should now be resolved as of 10.0.10 - https://stackblitz.com/edit/angular-gcf63x-njm62j

**Comment by puspendupalgsa** [comment]
@Bibek-Regmi  search MFE was upgraded to SDS 10.0.10 . We verified the issue is resolved.
