### ISSUE TITLE
Results List formatting

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#542]
**Components Involved**
sds-search-result-list

**Expected Behavior**
- Expect one horizontal line between each record.
- Values in first column to be inline with label.

**Actual Behavior**
- Has two horizontal lines between each record.
- Values in first column are on next line.  (This may have been intentional but it results in a lot of extra white space.)

**Your Environment**
Angular Version: 10.2.3
@gsa-sam packages version: 10.0.8, sam-styles 0.0.98

**Additional context**

sam-design-system site -- https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/site/gsa/sam-design-system/documentation/components/result-list/examples:
![image](https://user-images.githubusercontent.com/75684861/106525112-7af81600-64b1-11eb-9f04-deb1cdeca774.png)

BEFORE: Exclusions Tier 2 workspace with gsa-sam 10.0.4, sam-styles 0.0.94:
![image](https://user-images.githubusercontent.com/75684861/106525294-c27ea200-64b1-11eb-80aa-5164188021aa.png)

AFTER: Exclusions Tier 2 workspace with gsa-sam 10.0.8, sam-styles 0.0.98:
![image](https://user-images.githubusercontent.com/75684861/106525375-e346f780-64b1-11eb-9296-8ef2b31037b3.png)

**Comment by Bibek-Regmi** [comment]
The double horizontal line should be fixed as of latest release - 10.0.10, The remaining task for this is to left align the value for unique entity id with the DUNS and SAM tags rather than the current alignment with `Unique Entity ID` label.

**Comment by brandydanner-gsa** [comment]
Confirmed the double horizontal line has been fixed.

**Comment by cwolf10** [comment]
@brandydanner-gsa I updated documentation to correctly align the unique entity id to the DUNS/SAM tag. Please take a look and update as needed.
<img width="984" alt="Screen Shot 2021-03-15 at 3 05 58 PM" src="https://user-images.githubusercontent.com/72805180/111322561-70e43e00-863f-11eb-860c-b31b771179a4.png">

**Comment by brandydanner-gsa** [comment]
Closing this ticket as the issues have been resolved.  Thanks Bibek and Cameron.  I updated to the 10.0.16 packages and sam-styles 0.0.105, and updated the style classes for the DUNS and SAM values.
