### ISSUE TITLE
Support for autocomplete in subheader

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#577]
**Components Involved**
sds-subheader, sds-autocomplete

**Expected Behavior**
sds-autocomplete can be used instead of sds-search in sds-subheader

**Actual Behavior**
When using sds-autocomplete instead of sds-search in sds-subheader, there are a few issues: 
1) The autocomplete is pushed to the left against the Back button and Title.
2) Width of the autocomplete text box cuts off the placeholder text.
3) On page load, the placeholder text is blank when there is no subheader button.  When I click somewhere on the page, the placeholder text then appears.  However if there is a subheader button, the placeholder text is there on page load.

**Your Environment**
Angular Version: 10.2
@gsa-sam packages version: 10.0.9, sam-styles 0.0.99

**Additional context**

1) The autocomplete is pushed to the left against the Back button and Title.

![image](https://user-images.githubusercontent.com/75684861/107969022-2490da00-6f7d-11eb-8217-c822b5e14789.png)

2) Width of the autocomplete text box cuts off the placeholder text.

3) On page load, the placeholder text is blank when there is no subheader button.  When I click somewhere on the page, the placeholder text then appears.  However if there is a subheader button, the placeholder text is there on page load.

![image](https://user-images.githubusercontent.com/75684861/107969279-8f421580-6f7d-11eb-98eb-d6d78f2e265f.png)

_After I click on the page:_
![image](https://user-images.githubusercontent.com/75684861/107969322-a2ed7c00-6f7d-11eb-834e-3edb62e82acc.png)

Code sample:
![image](https://user-images.githubusercontent.com/75684861/107970361-04621a80-6f7f-11eb-9170-e5e19c433c42.png)

**Comment by yerramshilpa** [comment]
This feature is implemented and it is available in @gsa-sam/layouts@10.0.34 version
