### ISSUE TITLE
Accessibility checks using JAWS for pagination component (sds-pagination)

### ISSUE THREAD

**Issue by SeanKimGSA** [GSA/sam-design-system#585]
**Components Involved**
 sds-pagination

**Expected Behavior**
1. In T2 workspace, when JAWS is reading pagination, should narrate "*page number of *total page number"
2. When changing pages using page arrows, Jaws should indicate results have changed, or any change has happened.

**Actual Behavior**
1. JAWS skips the number of pages when reading 1 'of 4' (it skips the 'of 4' part).
2. After clicking the page arrows, JAWS doesn't indicate the results have changed or anything happened.

**Your Environment**
Angular Version: X.Y.Z
Angular: 10.2.3

@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
"@gsa-sam/components": "10.0.9",
"@gsa-sam/layout": "10.0.10",
"@gsa-sam/layouts": "10.0.9",
"@gsa-sam/sam-formly": "10.0.9",
"@gsa-sam/sam-material-extensions": "10.0.9",
"@gsa-sam/sam-styles": "0.0.99",
"@gsa-sam/shared": "10.0.10",

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/79326342/108539568-2aa0f680-72ae-11eb-8319-e737c5734664.png)

**Comment by Bibek-Regmi** [comment]
For number 1 - Updated so that JAWS will announce total page number on focus. That way the user knows the maximum value they can enter - Will be fixed in 10.0.12 release
For number 2 - Should be resolved in 10.0.11
