### ISSUE TITLE
Accessibility checks using JAWS for filters component (sds-filters)

### ISSUE THREAD

**Issue by SeanKimGSA** [GSA/sam-design-system#586]
**Components Involved**
 sds-filters

**Expected Behavior**
1. In T2 workspace, when JAWS is reading side-nav search fields, should narrate that each field/filter is a search field.
2. If you hit enter on a filter/search field, JAWS should indicate the search results have changed or refreshed.
3. Clicking "Reset All" in side-nav filters, JAWS should indicate results have changed/refreshed.

**Actual Behavior**
1. Side-nav free text search fields: JAWS doesn't indicate each is a search field or filter (other than 'Search by Keyword.') For example, CAGE reads: "CAGE/NCAGE edit, type and text"
2. If you hit enter on a filter/search field, JAWS doesn't indicate the search results have changed or refreshed.
3. After clicking "Reset All," JAWS doesn't indicate the results have changed or refreshed.

**Your Environment**
Angular Version: X.Y.Z
Angular: 10.2.3

@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
"@gsa-sam/components": "10.0.9",
"@gsa-sam/layout": "10.0.10",
"@gsa-sam/layouts": "10.0.9",
"@gsa-sam/sam-formly": "10.0.9",
"@gsa-sam/sam-material-extensions": "10.0.9",
"@gsa-sam/sam-styles": "0.0.99",
"@gsa-sam/shared": "10.0.10",

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/79326342/108541154-1fe76100-72b0-11eb-9ddf-f97a2a6b0544.png)

**Comment by Bibek-Regmi** [comment]
Issue number 2 & 3 resolved. Number 1 is not an accessibility concern - so long as the labels are being read correctly to the user
