### ISSUE TITLE
SearchMFE code base - noResultsFinalMessageModel template not showing correctly. 

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#591]
**Components Involved**
"@gsa-sam/components": "10.0.10,
    "@gsa-sam/layouts": "10.0.10",
    "@gsa-sam/sam-formly": "10.0.10",
    "@gsa-sam/sam-material-extensions": "10.0.10"

**Expected Behavior**
![image](https://user-images.githubusercontent.com/74928453/108772104-d13cff80-7519-11eb-9a74-5dd64309d79c.png)

**Actual Behavior**

![image](https://user-images.githubusercontent.com/74928453/108772148-def28500-7519-11eb-8eb5-cf5e50a782f7.png)

Instead of showing the noResultsFinalMessageModel (as in the Expected behavior), it's showing a default message. 

**Your Environment**
Angular Version: 10.2.3
@gsa-sam packages version: 
    "@gsa-sam/components": "10.0.10,
    "@gsa-sam/layouts": "10.0.10",
    "@gsa-sam/sam-formly": "10.0.10",
    "@gsa-sam/sam-material-extensions": "10.0.10"

**Comment by yerramshilpa** [comment]
@alexkamien I was able to fix the issue and I will be available on Monday's release
