### ISSUE TITLE
Responsive mobile mode - Filters "Reset All" does not work for filters already populated on Advanced Search open

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#594]
**Components Involved**
sds-side-toolbar, sds-filters

**Expected Behavior**
When using filters in Responsive toolbar in Mobile mode, I expect that I can clear previously applied filters when I click "Reset All".

**Actual Behavior**
When using filters in Responsive toolbar in Mobile mode, I cannot clear previously applied filters when I click "Reset All".  Only filters that I set after clicking "Advanced Search" are cleared using "Reset All".  Once I click "Apply" and reopen the filters using "Advanced Search" the previous filters do not clear with "Reset All".  In fact, the previous filters are restored if I clear the values.

**Your Environment**
Angular Version: 10.2
@gsa-sam packages version: 10.0.9 locally, demo on Design System Site

**Additional context**
Steps to reproduce:
1) Go to "Responsive Layout" demo on Design System Site:  https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/site/gsa/sam-design-system/documentation/layout-responsive?page=1&sort=legalBusinessName
2) Use Mobile view in Chrome Dev Tools
3) Click "Advanced Search". Expand "Status" accordian, check "Active" checkbox. Click "Reset All". **Checkbox is cleared correctly.**
4) Expand "Status" accordian, check "Active". Click "Apply".
5) Click "Advanced Search" again.  You'll see the Status > Active checked.  Click "Reset All".  **Checkbox is not cleared.**
6) Check the Status > Inactive checkbox.  Click "Reset All".  **Only the "Inactive" checkbox is cleared.**
7) Uncheck Status > Active. Click "Reset All". **The "Active" checkbox is now checked again.**

**Comment by Bibek-Regmi** [comment]
@brandydanner-gsa - Proper resolution on this will require some change on application side as well. We've updated sds-filters to take in a `[defaultModel]` input - this represents the default values of the filters, when is what the form will be reset to if passed in. Please update on your side to also pass in default model value to sds-filters, and the reset filters should behave consistently.
We've updated the documentation to include an example. Please see `Components` -> `Filters` -> Scroll down to `DefaultModel` example - https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/site/gsa/sam-design-system

**Comment by brandydanner-gsa** [comment]
I confirmed this issue is fixed with packages 10.0.15 and making the application side changes for defaultModel.  Closing this ticket.
