### ISSUE TITLE
Side Nav 508 role issue

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#608]
**Components Involved**
sds side navigation 

**Expected Behavior**
the component should include a role = navigation 

**Actual Behavior**
component does not include role = navigation

**Your Environment**
Angular Version: 10.2.2
@gsa-sam packages version:
sds 10.0.11

**Additional context**
![image](https://user-images.githubusercontent.com/79877133/109724443-92dcbb80-7b7d-11eb-936a-17f540aebe97.png)

**Comment by Bibek-Regmi** [comment]
A `nav` html markup implies role=navigation - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role
`It is preferable to use the HTML5 <nav> element to define a navigation landmark. If the HTML5 nav element technique is not being used, use a role="navigation" attribute to define a navigation landmark.`
