### ISSUE TITLE
Manually updating sds filters value changing reset all behavior

### ISSUE THREAD

**Issue by Bibek-Regmi** [GSA/sam-design-system#609]
**Components Involved**
sds-filters

**Expected Behavior**
Calling updateSearchResultsModel in search list layout should properly updates the filter, but it should not impact resetAll behavior

**Actual Behavior**
Calling updateSearchResultsModel in search list layout properly updates the filter, but it also modifies the default values in such a way that clicking resetAll keeps the updated filter value

**Your Environment**
Angular Version: 10+
@gsa-sam packages version: 10.0.11+

**Additional context**
https://stackblitz.com/edit/angular-taq2mg?file=src%2Fapp%2Fautocomplete-freetext.component.ts

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa  - this was in reference to the resetAll not working properly with keyword entered in subheader - Should be working as of 10.0.15. Alternatively, another input has also been added to sdsFilters called `[defaultModel]` which refers to what the model should default to when resetAll is clicked - feel free to pass your defaultModel in as added layer. Please validate this is no longer an issue with 10.0.15 and confirm. Feel free to close this ticket out if it is no longer an issue

**Comment by jesseboydgsa** [comment]
updated libs to 10.0.15 and when i go to opp -> use header search box 'test' -> hit  'reset all' -> no change

**Comment by jesseboydgsa** [comment]
we resolved this issue by not changing the reference to filtermodel which was updating the 'initialValue' of fomly to include the keyword.  instead just provide updateSearchResultModel with a local variable filterModel not this.filterModel
