### ISSUE TITLE
Accessibility Issue - Formly-radio component not generating accessible name

### ISSUE THREAD

**Issue by ArdonPolukoff** [GSA/sam-design-system#621]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
Formly-radio

**Expected Behavior**
How you expect the listed component(s) to function
Expected the role tag to have a mechanism that generates an accessible name for 508 compliance.

**Actual Behavior**
How the listed component(s) actually function
Access assistant the finds two errors when testing the Formly-radio component.

1. This FORM (role=radiogroup) does not have a mechanism that allows an accessible name value to be calculated.
2. The role attribute value given to this FORM is not allowed.  This element's role attribute can be set to one of the following text values: search |  region; Or the role attribute can be removed.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
"@gsa-sam/components": "10.0.12",
    "@gsa-sam/layout": "10.0.12",
    "@gsa-sam/layouts": "10.0.12",
    "@gsa-sam/sam-formly": "10.0.12",
    "@gsa-sam/sam-material-extensions": "10.0.12",
    "@gsa-sam/sam-styles": "0.0.102",
    "@gsa-sam/shared": "10.0.10",

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/58925707/110356390-37408100-8008-11eb-85c9-40a8a03a5cb5.png)

![image](https://user-images.githubusercontent.com/58925707/110356425-40315280-8008-11eb-9b67-54c9db449b24.png)

**Comment by Bibek-Regmi** [comment]
@ArdonPolukoff - Mentioned issues should be resolved as of 10.0.15 - form should no longer have radio group role. Additionally, you should now be able to pass in ariaLabel or label property through the formly's templateOptions settings and provide it an accessible label. Please validate and confirm, and if this is no longer an issue, feel free to close out the ticket

**Comment by ArdonPolukoff** [comment]
Hi Bibek,  The initial problem with the FORM having a role of radiogroup has been resolved with the update to 10.0.15.  

I do see a new problem.

![image](https://user-images.githubusercontent.com/58925707/110873404-ac79b380-829f-11eb-8447-b2c148cf99a0.png)

If i am understanding the note correctly the aria-describedby attribute value of 'requestType-description' is either incorrect or in use somewhere else. Can that value be changed to something else?

**Comment by Bibek-Regmi** [comment]
@ArdonPolukoff - For the radio buttons that are being flagged here, can you confirm whether or not a description value is given? It might be the case that no description is given, and a describedBy is still being set. In which case, it would be on SDS to only conditionally have the describedBy attribute on our radio formly

**Comment by ArdonPolukoff** [comment]
Hi Bibek. the description value was being given in the exclusion-filters.component.ts file. After removing the id field in the fields array the aria-describedby attribute switched to displaying " formly_9_radio_requestType_0".   
![image](https://user-images.githubusercontent.com/58925707/111228109-0d63fd00-85ba-11eb-9a94-af07ef7d9340.png)
Could you explain how the described by attribute is finding that?

**Comment by Bibek-Regmi** [comment]
@ArdonPolukoff - The describedBy attribute uses an id that is autogenerated by formly. You can override this by passing in your own id through formly config. In the screenshot above, it simply adds `-description` as suffix to id.  I've updated logic from our side to only have describedBy if there is a description on the radio form on version 10.0.16+. However, if the radio group already contains a description, then that logic change should not have any impact for the issue you are seeing. If you are not currently doing so, try passing in an id through the formly field config for that radio.

**Comment by ArdonPolukoff** [comment]
@Bibek-Regmi updating the @gsa-sam/sam-formly package from 10.0.15 to 10.0.16 fixes the issue. Thanks for looking into this for me!
