### ISSUE TITLE
sds-toolbar and sds-accordion cutting off text for cba domain

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#622]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-toolbar  and sds-accordion

**Expected Behavior**
How you expect the listed component(s) to function
expect accordion to accommodate all text correctly

**Actual Behavior**
How the listed component(s) actually function
text gets cut off

![image](https://user-images.githubusercontent.com/58823468/110365335-c3977780-7ff9-11eb-974c-5392c4cd2395.png)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/58823468/110365463-ee81cb80-7ff9-11eb-9e24-13494a872911.png)
in firefox
ng 10.2.3

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/58823468/110365963-88e20f00-7ffa-11eb-9a9c-83c4cecfd692.png)

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa - Should be resolved in 10.0.15 - please validate and confirm. Feel free to close the issue out if it is no longer an issue

**Comment by jesseboydgsa** [comment]
![image](https://user-images.githubusercontent.com/58823468/110843764-82070680-825d-11eb-8124-eb3eb4f21da2.png)

looks good in 10.0.15 thanks Bibek @Bibek-Regmi

**Comment by jesseboydgsa** [comment]
potential unintended consequence of update?  please look at the spacing of all the filters or is this a design change?
![image](https://user-images.githubusercontent.com/58823468/110845235-3bb2a700-825f-11eb-9294-e8518cd744e9.png)
