### ISSUE TITLE
Accordion text allignment - IE only issue

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#632]
**Components Involved**
sds accordion

**Expected Behavior**
Text should be centered within accordion 

**Actual Behavior**
Within IE, the text alignment is too high

**Your Environment**
Issue noted in SDS site (see screenshot)

**Ticket Number**
IAEDEV-48769

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![IE Accordion padding](https://user-images.githubusercontent.com/79877133/110853160-467e3380-8281-11eb-8363-7ffb4b5c3da5.JPG)

**Comment by Bibek-Regmi** [comment]
Resolved as of 10.0.18
![image](https://user-images.githubusercontent.com/73653244/114185614-ec21d280-9913-11eb-9b1c-88077389c8d1.png)
