### ISSUE TITLE
SDS search responsive issue

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#633]
**Components Involved**
SDS search

**Expected Behavior**
Search bar should be responsive on smaller view ports

**Actual Behavior**
Around 350px view port search bar does not adapt to smaller size

**Your Environment**
Issue found on SDS site
![SDS search responsiveness](https://user-images.githubusercontent.com/79877133/110856941-43d20d00-8286-11eb-99c7-ae9f5b0c7e98.JPG)

**Ticket Number**
IAEDEV-48776

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by cwolf10** [comment]
Demo has been updated as of 10.0.19 https://github.com/GSA/sam-design-system/releases/tag/v10.0.19. Please confirm and close. @rtencic-gsa

**Comment by rtencic-gsa** [comment]
Responsive search component is resolved. SDS-search-big has decreased in size which I will open a separate ticket for.
