### ISSUE TITLE
508 Issue with Video component creating duplicate divs/ids

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#641]
**Components Involved**
SDS Video component

**Expected Behavior**
No duplicate divs created from video component

**Actual Behavior**
Duplicate divs are generated with same id triggering a 508 defect

Error- This DIV has an id attribute of 'px-aria-announce', which is not unique in the same DOM

<div style="overflow: hidden; text-indent: -999999px;" aria-atomic="true" role="alert" id="px-video-aria-announce"</div>

**Your Environment**
Angular Version: X.Y.Z
Sds v10.0.15

**Ticket Number**

IAEDEV-47469

**Additional context**

![508 video issue 1](https://user-images.githubusercontent.com/79877133/111338519-63ce4b80-864d-11eb-8d9b-8180cbe52ecb.JPG)
![508 video issue 2](https://user-images.githubusercontent.com/79877133/111338523-64ff7880-864d-11eb-815b-b4eb6270b58d.JPG)

**Comment by rtencic-gsa** [comment]
Having issues using update - adding additiona  AMP error details:

Error- This DIV has an id attribute of 'px-aria-announce', which is not unique in the same DOM

<div style="overflow: hidden; text-indent: -999999px;" aria-atomic="true" role="alert" id="px-video-aria-announce"</div>

**Comment by yerramshilpa** [comment]
@rtencic-gsa  Not able to  reproduce the issue with latest version.

**Comment by rtencic-gsa** [comment]
@yerramshilpa I can still re-create issue on SDS site, does that have latest version yet?

**Comment by yerramshilpa** [comment]
This is issue is resolved in @gsa-sam/components@10.0.25 version

**Comment by rtencic-gsa** [comment]
Issue resolved
