### ISSUE TITLE
Bottom of filter radio button cut off with filterwrapper

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#644]
**Components Involved**
sds-filters (using Formly), sds-side-toolbar

**Expected Behavior**
Filter radio buttons are fully visible and not cut off

**Actual Behavior**
Bottom of filter radio button is cut off when the field is using the `filterwrapper` and not the `accordionwrapper`.  Functionality is not affected.

**Your Environment**
Angular Version: 10.2
@gsa-sam packages version: 10.0.16, sam-styles 0.0.105

**Ticket Number**
IAEDEV-49165

**Additional context**

The "My Exclusions" radio button is cut off at the bottom:

![image](https://user-images.githubusercontent.com/75684861/111690322-6c688280-8803-11eb-989a-90455bf6a02e.png)

Formly config:

 fields: FormlyFieldConfig[] = [
    {
      key: 'requestTypesOptions',
      wrappers: ['filterwrapper'],
      templateOptions: {},
      fieldGroup: [
        {
          key: 'requestType',
          id: 'requestType',
          type: 'radio',
          defaultValue: 'myexclusions',
          templateOptions: {
            label: 'Exclusions Type',
            labelClass: 'usa-sr-only',
            hideOptional: true,
            options: [
              { label: 'Agency Exclusions', value: 'myagencyexclusions' },
              { label: 'My Exclusions', value: 'myexclusions' }
            ]
          }
        }
      ]
    },
    {
      key: 'searchKeyword',
      wrappers: ['accordionwrapper'],
      templateOptions: { label: 'Search by Keyword' },
      fieldGroup: [{
        key: 'keywordSearch',
        type: 'input',
        id: 'keyword',
        templateOptions: {
          label: 'Keyword',
          placeholder: '',
          inputType: 'text',
          hideOptional: true,
        }
      }],
    },
  ];

**Comment by yerramshilpa** [comment]
@brandydanner-gsa , the issue is with the old wrapper, can you use the group instead of wrappers. Below is the updated code, for example, let me know if you still have the same issue after the update. 

 {
      key: 'requestTypesOptions',
      **//wrappers: ['filterwrapper'],**
      templateOptions: { label: 'date', **group: 'panel'** },
      fieldGroup: [
        {
          key: 'requestType',
          id: 'requestType',
          type: 'radio',
          defaultValue: 'myexclusions',
          templateOptions: {
            label: 'Exclusions Type',
            labelClass: 'usa-sr-only',
            hideOptional: true,
            options: [
              { label: 'Agency Exclusions', value: 'myagencyexclusions' },
              { label: 'My Exclusions', value: 'myexclusions' },
            ],
          },
        },
      ],
    },

**Comment by brandydanner-gsa** [comment]
@yerramshilpa I confirmed using the group instead of wrappers has fixed the issue.  Closing this ticket.  Thanks!
