### ISSUE TITLE
ExternalLinkDirective issue with set aria-labels -508 issue

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#645]
**Components Involved**
ExternalLinkDirective

**Expected Behavior**
When we set an arial-label for a link while also using the external link directive, the set aria-label ovverrides any aria-label settings from directive

**Actual Behavior**
When we set an aria-label for a link while also using the external link directive, the set aria-label is being set to blank

**Your Environment**

@gsa-sam 10.0.17-beta.0

**Additional context**
Screenshot without directive applied
![image](https://user-images.githubusercontent.com/79877133/111832119-c1b99800-88c6-11eb-9cbc-a0d13c922161.png)

Screenshot with directive applied
![image](https://user-images.githubusercontent.com/79877133/111832148-caaa6980-88c6-11eb-9f00-f38336d56bc3.png)

**Comment by yerramshilpa** [comment]
@rtencic-gsa  The issue has been resolved in @gsa-sam/components@10.0.17 version.

**Comment by rtencic-gsa** [comment]
Provided Aria-label is now allowed and working as expected.
