### ISSUE TITLE
Accessbility findings for modal dialogs

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#650]
**Components Involved**
SdsDialogService, sds-side-toolbar

**Expected Behavior**
Modal dialogs meet accessibility requirements.

**Actual Behavior**
Modal dialogs have findings using the Access Assistant Chrome plug-in.  See the Additional context for findings.

**Your Environment**
Angular Version: 10.2
@gsa-sam packages version: 10.0.17, sam-styles 0.0.105

**Ticket Number**
IAEDEV-49270

**Additional context**
1) "Avoid placing inactive elements in the focus order" - occurs on all modal dialogs, including our custom Download modal and the SDS Mobile responsive modal (Advanced Search).

![image](https://user-images.githubusercontent.com/75684861/112342189-66a5ed80-8c98-11eb-9cce-e1c94bc8e04d.png)
![image](https://user-images.githubusercontent.com/75684861/112342298-7c1b1780-8c98-11eb-9ac4-b502fdca4c84.png)
![image](https://user-images.githubusercontent.com/75684861/112342434-98b74f80-8c98-11eb-85e2-e11638f0bb91.png)

2) "Provide a descriptive dialog title" - On responsive modal dialog component. We previously fixed this finding on the Download modal dialog by passing an ariaLabel to the configuration. However, the responsive Modal dialog is part of the Design System component and not configurable in our code. I can add a workaround by setting this in the onDialogOpen function, but it would be better if it was fixed in the component.

![image](https://user-images.githubusercontent.com/75684861/112342757-dfa54500-8c98-11eb-9f16-83777334f0d9.png)
![image](https://user-images.githubusercontent.com/75684861/112342941-11b6a700-8c99-11eb-995b-dd12ed98dc8a.png)
![image](https://user-images.githubusercontent.com/75684861/112343106-314dcf80-8c99-11eb-9825-d77a50606f28.png)

**Comment by Bibek-Regmi** [comment]
@brandydanner-gsa - Issue #1 is a known false flag from amp - the div it's flagging is there in order to trap focus and does not cause accessibility issues
For issue #2, next release (10.0.19) will update the toolbar component such that users can pass in their own config options for the dialog, allowing you to pass in aria label or any other custom config you might want.

**Comment by brandydanner-gsa** [comment]
@Bibek-Regmi  Confirming Issue 2 has been resolved with 10.0.19 and adding the ariaLabel config options for the toolbar dialogs.  Closing this issue.  Thanks!
