### ISSUE TITLE
the logic that handles defaultFilterValue appears to remove false values

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#656]
**Components Involved**
search-list-layout

**Expected Behavior**
To keep the object as is in the defaultFilterValue prop

**Actual Behavior**
removes in this case is_inactive: false prop

**Your Environment**
Angular Version: 10
@gsa-sam packages version: 10.0.17

**Ticket Number**
IAEDEV-49164

**Additional context**
On load filterChange and filters object
![image](https://user-images.githubusercontent.com/66032295/113329482-a057a380-92eb-11eb-9cd8-bdd4954739f6.png)
![image](https://user-images.githubusercontent.com/66032295/113329744-f0366a80-92eb-11eb-9dc7-3152fc7c4ebc.png)

**Comment by puspendupalgsa** [comment]
![image](https://user-images.githubusercontent.com/66069671/114596978-3c739a00-9c5e-11eb-86ec-f86ae8583487.png)
Refreshing the URL on default values does not show the "Select Criteria" message, instead returns all rows matching default filter values.

**Comment by puspendupalgsa** [comment]
We had a quick discussion with @Bibek-Regmi  and there is a possibility that these are related
