### ISSUE TITLE
Browser back button fails to return to the correct page number

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#664]
**Components Involved**
SearchListLayout

**Expected Behavior**
change page from 1 to 2 then 3 then hit back button.  Expected behavior is to go back from page 3 to 2 

**Actual Behavior**
Appears to be a design issue with history turned on.  Tested in design prototype and the issue is there see https://federalist-e1ade7fb-52e9-46c3-b273-1ab1fd05e2fa.app.cloud.gov/site/gsa/sam-prototypes/#/search?index=assistancelist&page=1&sort=relevanceDescending&sfm%5Bkeyword%5D=f change page from 1 to 2 then 3 then hit back button.  Expected behavior is to go back from page 3 to 2 but always returns to page 1. 

**Your Environment**
![image](https://user-images.githubusercontent.com/58823468/113911042-5c9ee700-978e-11eb-9524-1c96b85880ba.png)

**Ticket Number**
IAEDEV-48163

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa - This should be resolved in our latest version. Please validate when able, and feel free to close out if it's no longer an issue.
