### ISSUE TITLE
508 compatibility change

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#665]
**Components Involved**
FormlyActionButtonGroupComponent

**Expected Behavior**
Allow for an aria-label to be added into the highlighted 'input' tag (screenshot added). 

**Actual Behavior**
Aria-label is not supported, which creates issues during WAVE testing. 

**Your Environment**
Angular Version: 10.2.3
"@gsa-sam/components": "10.0.20",
"@gsa-sam/layout": "10.0.37",
"@gsa-sam/layouts": "10.0.20",
"@gsa-sam/sam-formly": "10.0.20",
"@gsa-sam/sam-material-extensions": "10.0.20",
 "@gsa-sam/sam-styles": "0.0.108",
 "@gsa-sam/shared": "10.0.18",

**Ticket Number**
https://cm-jira.usa.gov/browse/IAEDEV-49409

**Additional context**
In the exclusion domain, we are using the "actionbuttongroup.ts" component for one of the navigation filters. With my understanding, the component does not support additions of aria-labels for screen readers to pick up, thus, we have having issues coming up on WAVE testing.

I attached a picture of the "actionbuttongroup.ts" file, and highlighted the <input> tag that is being used. My proposed solution is to add an aria-label="option.label" to the input tag, which will solve the 508 issue we are having. This solution should not affect any other functionality, as the label field on option is already defined and aria-label does not change any views.  

I'm also attaching a picture of the WAVE test. As well as a picture of the object we are creating to be used with the actionbuttongroup. I have tried to alter fields in the object on our end but it looks like the design component does not support aria-labels. 

<img width="1464" alt="Screen Shot 2021-04-06 at 1 15 13 PM" src="https://user-images.githubusercontent.com/74928453/114125096-02e40d00-98b3-11eb-8c4a-51d45e32e6a2.png">

![method](https://user-images.githubusercontent.com/74928453/114125231-3cb51380-98b3-11eb-9043-5150ed58fa65.PNG)

![wave-test](https://user-images.githubusercontent.com/74928453/114125293-62dab380-98b3-11eb-90a1-a2887617a622.PNG)

**Comment by Bibek-Regmi** [comment]
@alexkamien - Sam Design System does not support the component you have in the screenshot - that formly component is created by search MFE and should be resolved by search MFE. Looking at the screenshot, the label tag's [attr.for] points to a variable called 'id' while the input's id points to a variable called 'option.key'. The label's 'for' attribute should contain the same value as the id of the input element it's for.

**Comment by alexkamien** [comment]
thank you for the clarification @Bibek-Regmi
