### ISSUE TITLE
More Filters component displaying filter for empty object.

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#666]
**Components Involved**
"More Filters" component in SearchMFE.

**Expected Behavior**
If passed in empty object, {}, it should not display in the more filters component. 

**Actual Behavior**
It is displayed as a checkbox with empty field (screenshot attached).  

**Your Environment**
Angular Version: 10.2.3
    "@gsa-sam/components": "10.0.20",
    "@gsa-sam/layout": "10.0.37",
    "@gsa-sam/layouts": "10.0.20",
    "@gsa-sam/sam-formly": "10.0.20",
    "@gsa-sam/sam-material-extensions": "10.0.20",
    "@gsa-sam/sam-styles": "0.0.108",
    "@gsa-sam/shared": "10.0.18",

**Ticket Number**
Will create once fix is released. 

**Additional context**
Our team has been given requirements to remove status filters based on user permissions. To achieve this, I am passing in an empty object "{}", which allows us to "hide" the status filter on the side-nav configuration. Here is a picture of the method that returns an empty object based on Exclusion domain.
![statusConfig](https://user-images.githubusercontent.com/74928453/115637365-39675200-a2cd-11eb-9913-56e03a3aeaa2.PNG)

Other options were considered, such as making changes in the main configuration file, shown here.
![search-filters-config (1)](https://user-images.githubusercontent.com/74928453/115637420-5865e400-a2cd-11eb-9f02-9b032c382932.PNG)

The problem with making the change in the above file, is that the current behavior is set to only run once on application start. So when a user logs in, the initialized configurations don't change. Having the configurations reload when a user logs in/out, would drastically affect performance, which doesn't seem justified just to add/remove a status filter. 

The problem with passing in an empty object, {}, is that the "more filters" option on the side-navigation shows an empty checkbox with no label. I am requesting a change in the design component that doesn't display any field in the "more filters" when passed an empty object. 

<img width="1287" alt="Screen Shot 2021-04-09 at 7 25 35 AM" src="https://user-images.githubusercontent.com/74928453/114180659-b70a8580-98fd-11eb-91c0-91cd8965f6ea.png">

**Comment by yerramshilpa** [comment]
The feature is implemented  in the @gsa-sam/sam-formly@10.0.25 version
