### ISSUE TITLE
Download Modal - AMP testing defect SFE

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#667]
**Components Involved**
sam-modal

**Expected Behavior**
2 issue's noticed when AMP testing the download modal in SFE related to the html structure of the page. 

**Actual Behavior**
Html structure should not have issue's during AMP tests. 

**Your Environment**
Angular Version: 10.2.3
"@gsa-sam/icons": "1.0.0",
    "@gsa-sam/layout": "10.0.37",
    "@gsa-sam/layouts": "10.0.20",
    "@gsa-sam/sam-formly": "10.0.20",
    "@gsa-sam/sam-material-extensions": "10.0.20",
    "@gsa-sam/sam-styles": "0.0.108",
    "@gsa-sam/sam-ui-elements": "2.0.0-beta.8",
    "@gsa-sam/shared": "10.0.19",

**Ticket Number**
https://cm-jira.usa.gov/browse/IAEDEV-49408

**Additional context**
![h3-AMP-downloadModal](https://user-images.githubusercontent.com/74928453/115765529-205db000-a364-11eb-982d-a918704cb48b.PNG)
![div-AMP-downloadModal](https://user-images.githubusercontent.com/74928453/115765536-22277380-a364-11eb-92ce-495c4424e529.PNG)

**Comment by cwolf10** [comment]
HI @alexkamien,
The only content in the dialog that is provided by SDS is the x to close the dialog. Any other content being displayed is being provided by one of the MFEs, they will need to correct the HTML structure they are providing to the dialog.

**Comment by alexkamien** [comment]
Hi @cwolf10, sorry for any confusion in terms of the referred download modal. The issue's seem to show up because the download modal uses the following template attached to this message, which looks like it's not in the scope of the MFE's. 

![sam-modal](https://user-images.githubusercontent.com/74928453/114211986-8a1a9a80-991e-11eb-9a6a-83b8258ec641.PNG)

**Comment by Bibek-Regmi** [comment]
@alexkamien - This seems like it's using modal from sam-ui-elements. Would it be possible for you to update to using the modal from sam-design-system library? - https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/preview/gsa/sam-design-system - Components -> Modal Dialog on Nav sidebar

**Comment by alexkamien** [comment]
@Bibek-Regmi Thanks for the reply, I looked into updating the modal, and it will require a big effort on revamping the entire way the sam-front-end handles downloads. If that becomes a requirement, it can be done with coordination from all the teams working on sam-front-end, as all the domains use the current modal from sam-ui-elements. Since the change would be so major, it doesn't seem justified for the purpose of fixing two AMP issues. For the requirement of this JIRA ticket, it would only require two changes which are listed under the "Additional Context" section. (A change in the aria-describedby label as well as the <h3> tag).

**Comment by Bibek-Regmi** [comment]
@alexkamien  - Please update sam-ui-elements to 2.0.2 - The update to the modal will allow you to pass in desired header level. Also for the duplicate/invalid id, please make sure you're also passing in an id value to the modal. You can see the changes for the update here - https://github.com/GSA/sam-ui-elements/pull/532/files
