### ISSUE TITLE
Autocomplete overlap for long names

### ISSUE THREAD

**Issue by bkmurray** [GSA/sam-design-system#676]
**Components Involved**
Autocomplete (Single Select)

**Expected Behavior**
I would expect the text for the selected value to be cut off before the 'x' to clear the autocomplete so that the 'x' is visible and users are able to identify and use it.

**Actual Behavior**
Currently the Autocomplete allows the text to overlap with the 'x' and it is hidden in the text

**Your Environment**
Current sam-ui-common packages since this issue was first reported in the Agency Picker
Angular Version: 10.2.1
@gsa-sam packages version: 10.0.20(Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-38252

**Additional context**
Agency Picker example
![image](https://user-images.githubusercontent.com/18359224/114761935-25e94380-9d2f-11eb-9677-fb1854d906c6.png)

Recreation on the Design Site (though this is hard to claim as the same issue since I had to manipulate the page a lot to get the box small enough)
![image](https://user-images.githubusercontent.com/18359224/114762202-7c568200-9d2f-11eb-9de1-47f7cd4f2054.png)

**Comment by yerramshilpa** [comment]
The issue has been resolved in @gsa-sam/sam-formly@10.0.25 version
