### ISSUE TITLE
sds-auto complete -508 missing Form label for Zipcode filter.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#682]
**Components Involved**
sds-auto complete

**Expected Behavior**
Assistance Listing MFE page should not have any Wave Errors. A form control should have a corresponding label.

Assumption: A form control need to have a corresponding label.

**Actual Behavior**
Wave is showing error for Zipcode filter - Missing form label. A form control does not have a corresponding label.

**Your Environment**
SDS 10.0.20

**Ticket Number**
IAE-45223

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/82841107/115423053-7cd99780-a1cb-11eb-97f4-b74a81eb4572.png)

![image](https://user-images.githubusercontent.com/82841107/115423081-8531d280-a1cb-11eb-9ef9-26180a3ac627.png)

**Comment by Bibek-Regmi** [comment]
@Parulbpatel - If you are using autocomplete, you can define the ariaLabelText for it through settings. Please see design system docs - https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/site/gsa/sam-design-system - autocomplete example

**Comment by Bibek-Regmi** [comment]
Closing due to no response
