### ISSUE TITLE
'more filters' selecting header does not deselect sub items

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#684]
**Components Involved**
Sds Advanced Filters

**Expected Behavior**
When I select a sub category and then select the parent for all boxes to toggle on and off

**Actual Behavior**
once sub is clicked parent box seems to have no effect

**Your Environment**
Angular Version: 10
@gsa-sam packages version: 10.0.23

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-50223

**Additional context**
![image](https://user-images.githubusercontent.com/58823468/115577376-3b072a80-a279-11eb-8353-79b7f12b5681.png)

**Comment by yerramshilpa** [comment]
The issue has been resolved in @gsa-sam/sam-formly@10.0.25 version
