### ISSUE TITLE
508 Very Low Contrast Error - Hover on Action Menu links, "Here’s how you know" link in Header, and Footer links

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#685]
**Components Involved**
sds-actions-menu, sds-footer

**Expected Behavior**
When hovering over a link in the Actions Menu, "Here’s how you know" in Header, or Footer links, the foreground and background colors provide sufficient contrast.

**Actual Behavior**
When hovering over a link in the Actions Menu, "Here’s how you know" in Header, or Footer links, the WAVE Chrome extension indicates a "very low contrast" error between text and background colors.

**Your Environment**
Angular Version: 10.2
@gsa-sam packages version: 10.0.23, sam-styles 0.0.110

**Ticket Number**
IAEDEV-50444

**Additional context**

WAVE "very low contrast" errors

Action Menu:
![Action Menu](https://user-images.githubusercontent.com/75684861/115589695-28531c80-a29e-11eb-966c-dd4708b95d2a.PNG)

Footer Links:
![Footer Links](https://user-images.githubusercontent.com/75684861/115589720-2db06700-a29e-11eb-9aa7-8828cab4e9f4.PNG)

An official website of the United States government - Here’s how you know
![image](https://user-images.githubusercontent.com/75684861/122583400-2d76e280-d027-11eb-9961-b422ba7c210e.png)

**Comment by yerramshilpa** [comment]
Footer link color code has been updated in @gsa-sam/sam-styles@0.0.115 version

**Comment by brandydanner-gsa** [comment]
Hi Shilpa, I see the contrast error is resolved on the footer link, but WAVE testing still shows a Contrast Error on the Action Menu links and the "Here’s how you know" link in Header.

**Comment by yerramshilpa** [comment]
Action menu hover color is resolved in @gsa-sam/sam-styles@0.0.116 version
