### ISSUE TITLE
ExternalLinkDirective arial label update for integration with dynamic links

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#688]
**Is your feature request related to a problem? Please describe.**
Content MFE is would like to integrate the Dynamic Links API service with the external link directive so that external link behavior is controlled in one location (instead of DB values) and will not require updates in multiple spots if change is requested.

**Describe the desired solution**
Update in logic of externalLinkDirective to append (opens in new window) to the aria label if applicable based on external link directive behavior for what should be an external link. Links will have aria label set on application side.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Bibek-Regmi** [comment]
@rtencic-gsa - This behavior should be implemented as of 10.0.27 - Please confirm and close whenever your team updates and validates
