### ISSUE TITLE
SearchMFE - 508 Accessibility - WAVE issues for Entity Information domain

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#689]
**Components Involved**
sds-toolbar

**Expected Behavior**
Expecting no WAVE issues when Entity Information domain is selected. 

**Actual Behavior**
The color scheme used for the left navigation once Entity Information domain is expanded creates 3 WAVE issues

**Your Environment**
Angular Version: 10.2.3
"@gsa-sam/components": "10.0.20",   
 "@gsa-sam/layout": "10.0.37",   
 "@gsa-sam/layouts": "10.0.20",  
 "@gsa-sam/sam-formly": "10.0.20",    
"@gsa-sam/sam-material-extensions": "10.0.20",   
 "@gsa-sam/sam-styles": "0.0.108",      
 "@gsa-sam/shared": "10.0.19",

**Ticket Number**
IAEDEV-50410

**Additional context**
![contrast-errors](https://user-images.githubusercontent.com/74928453/115636549-6d417800-a2cb-11eb-87ae-962b0931e85e.PNG)

**Comment by Bibek-Regmi** [comment]
This issue should be resolved as of sam-styles 0.111 and sds components 10.0.26
