### ISSUE TITLE
Sds-Video controls have low contrast highlight when tabbed 

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#690]
**Components Involved**
Sds-video

**Expected Behavior**
While tabbing through the video component, there should be a more prominent visual display of the highlighted video control  to indicate the tab position for a sighted keyboard user

**Actual Behavior**
There is a thin, dotted outline of the highlighted video control which is difficult to see

**Your Environment**
SDS component website

**Ticket Number**
IAEDEV-50471

IAE-XYZ

**Additional context**
![image](https://user-images.githubusercontent.com/79877133/115640419-e13c4a00-a2e4-11eb-84db-7d202b5c7879.png)

**Comment by yerramshilpa** [comment]
The issue has been resolved in the @gsa-sam/components@10.0.25 version

**Comment by rtencic-gsa** [comment]
Issue resolved
