### ISSUE TITLE
SDS Search Form Submit Issue

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#696]
**Components Involved**
sds-search formly searchForm

**Expected Behavior**
submit callback should execute

**Actual Behavior**
submit callback does does execute on click or hitting enter.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam/components@10.0.22
@gsa-sam/layouts@10.0.22
@gsa-sam/sam-material-extensions@10.0.22
@gsa-sam/sam-formly@10.0.22
@gsa-sam/sam-styles@0.0.110

**Ticket Number**
IAEDEV-50478

**Additional context**
![image](https://user-images.githubusercontent.com/79877133/116135918-b0229780-a69f-11eb-8145-6a1f64b98e19.png)

**Comment by yerramshilpa** [comment]
@rtencic-gsa  submit is an event for the formly-form, here is the guidance for the submit 

<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form"></formly-form>
  <button type="submit" class="btn btn-primary submit-button" [disabled]="!form.valid">Submit</button>
</form>

**Comment by rtencic-gsa** [comment]
This is an implementation issue - closing out ticket.
