### ISSUE TITLE
History in search-list-layout is overriding url fragment

### ISSUE THREAD

**Issue by nishantg95** [GSA/sam-design-system#700]
**Components Involved**
Search List layout

**Expected Behavior**
Adding a fragment at the end of the URL should redirect the page to internal anchor link. Fragment should persist in the URL by ending with #id

**Actual Behavior**
Fragment gets absorbed inside queryparams and triggers a search query

**Your Environment**
Angular Version: 10.2.3
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
@gsa-sam/components: "10.0.23",
@gsa-sam/layout: "10.0.40",
@gsa-sam/layouts: "10.0.23",
@gsa-sam/sam-formly: "10.0.23",
@gsa-sam/sam-material-extensions: "10.0.23",
@gsa-sam/sam-styles: "0.0.110",
@gsa-sam/shared: "10.0.19",

**Ticket Number**
IAEDEV-50237

**Additional context**
Steps to reproduce the issue
Step 1: Go to search home page
![image](https://user-images.githubusercontent.com/15683402/116150188-b0736080-a6a8-11eb-8854-a09d69764b5c.png)

Step 2: Type a fragment address of a predefined anchor (in this case it would be main-container div)
![image](https://user-images.githubusercontent.com/15683402/116150625-37c0d400-a6a9-11eb-90df-9b6daf4b898e.png)
![image](https://user-images.githubusercontent.com/15683402/116150676-5030ee80-a6a9-11eb-9bb9-3219370a5ca6.png)

Step3: Hit enter, and the URL changes #main-container to %23main-container, and also shows all search results when there was no query provided
![image](https://user-images.githubusercontent.com/15683402/116151120-d5b49e80-a6a9-11eb-8a15-53e086ab059c.png)

**Comment by Bibek-Regmi** [comment]
Resolved as of 10.0.29
