### ISSUE TITLE
AMP Issues for sam-ui-elements

### ISSUE THREAD

**Issue by swarnakatta-reisys** [GSA/sam-design-system#702]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
PFA, mail with details description on AMP Issues
sam-fieldset-wrapper => AMP Issue 1 and 5

sds-footer => AMP Issue 3

sds-header => AMP Issue 4

sam-sds-search-autocomplete => AMP Issue 6.

**Expected Behavior**
How you expect the listed component(s) to function
Resolution to AMP Issues

**Actual Behavior**
How the listed component(s) actually function

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-32343
[DST Common Component Defects.zip](https://github.com/GSA/sam-design-system/files/6394761/DST.Common.Component.Defects.zip)

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
The issue has been resolved in @gsa-sam/component@10.0.29 version
