### ISSUE TITLE
search-list-layout isDefaultFilter bug

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#704]
**Components Involved**

search-list-layout

**Expected Behavior**

when there are no filters selected, when filters are null or when filters are default values => show 'select criteria'

**Actual Behavior**

using getCleanModel filterModel will be {} and not match default filter
without cleanModel filterModel will inflate with keys that have nulls and still be equivalent to the default filter

**Your Environment**
![image](https://user-images.githubusercontent.com/58823468/117076944-1c2e7c80-acec-11eb-81f9-bd0aa126ba7c.png)

**Ticket Number**
IAEDEV-50532

**Additional context**
with cleanModel
![image](https://user-images.githubusercontent.com/58823468/117077122-631c7200-acec-11eb-86cf-8eaf58d8fcc3.png)

without cleanModel - see agency picker is included in the model but is a null value but fails the isDefaultModel test and shows results prematurely
![image](https://user-images.githubusercontent.com/58823468/117077384-db833300-acec-11eb-93c9-f94c86010a1a.png)

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa - This is a won't fix issue - The behavior you're seeing where removing filters displays data is expected.
