### ISSUE TITLE
Add pageSize to the query string

### ISSUE THREAD

**Issue by PeterWhiteGSA** [GSA/sam-design-system#729]
Considering that the page number is stored as a query string, it only makes sense to store the page size as well. This will allow the user to maintain both what page they were on and the size of the page after clicking back from an item. The prop can be added like this:
![image](https://user-images.githubusercontent.com/84515469/120676106-56aa4700-c45b-11eb-887b-0658655c11a5.png)

The conditional will check if the value is both a numeric value and between 25 and 100 other default to 25. The search home component can handle the page size from there.

**Comment by cwolf10** [comment]
Hi @PeterWhiteGSA 10.0.31 includes an update to address this issue. Please confirm you are seeing the expected behavior upon updating. Thanks.

**Comment by PeterWhiteGSA** [comment]
Success: pageSize is now a default parameter on startup:
![image](https://user-images.githubusercontent.com/84515469/123872626-f80da700-d8fa-11eb-88a1-8e152d13e366.png)

Success: the page size select sets the pageSize param
![image](https://user-images.githubusercontent.com/84515469/123872657-022fa580-d8fb-11eb-993d-5efb267a2fc2.png)

Success: pageSize is maintained after clicking back from a selection
![image](https://user-images.githubusercontent.com/84515469/123872683-0a87e080-d8fb-11eb-9e29-99bdd3edb0ff.png)
![image](https://user-images.githubusercontent.com/84515469/123872696-0eb3fe00-d8fb-11eb-9290-083e0b84c32e.png)

Success: when a user types in a non-number into the pageSize it will display an error message and default to 25
![image](https://user-images.githubusercontent.com/84515469/123872740-1ecbdd80-d8fb-11eb-88fa-95e3c35744aa.png)

**Comment by PeterWhiteGSA** [comment]
Error: changing the pageSize without interaction with the filters submits an All Domain search with the new pageSize
![image](https://user-images.githubusercontent.com/84515469/123872859-43c05080-d8fb-11eb-91b6-d599a47b8afa.png)

Error: the user can submit numbers not present in the number select
![image](https://user-images.githubusercontent.com/84515469/123872888-4b7ff500-d8fb-11eb-85b0-d10133b44f07.png)

Error: there is no min or max for number chosen which can lead to errors
![image](https://user-images.githubusercontent.com/84515469/123872940-589ce400-d8fb-11eb-9997-e307819a2b77.png)

**Comment by cwolf10** [comment]
Hi @PeterWhiteGSA,

I spoke with my team today regarding the issues you have raised with the released implementation.

1) The submit behavior matches the behavior if a user were to change the pageSize via the UI. Given that, it makes sense that a submit would occur. If there is a scenario where this is not the case I can follow up on that.
2) While a user can submit a number that is not available in the page size dropdown the api endpoint which is called can enforce that only certain values are valid and handle how to enforce a value which is not in the dropdown. Given that one team may want to respond to this scenario differently than another team we want to keep the common component as flexible as possible.
3) Same as above, we want to keep the component as flexible as possible. The range of values, and api response will vary between teams and search.

**Comment by PeterWhiteGSA** [comment]
That's good to hear if the backend handles the number in the url itself
it'll work all the same.

**Comment by cwolf10** [comment]
Sounds like the solution is fine. Closing this issue.
