### ISSUE TITLE
sds-filters.component.ts checkForHide nested fieldGroup issue

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#733]
**Components Involved**
sds-filters.component.ts 

**Expected Behavior**
inside the dates accordion, 2 date filters are shown
when i select a filter value, I expect the 2 hidden date filters will stay hidden

**Actual Behavior**
when i select a date filter from the visible date filter, all hidden date filters are revealed.

I believe this is because we have 3 levels deep and the checkForHide method thinks the middle level is a parent and turns hide:true to hide:false
the dates model appears to go from 2 dates with empty objects { } to 4 dates with empty obj { }

levels
dates accordion, date select filter(s) , custom dates filter (optional)

Prototype does not have a 3rd level custom date filter reveal

**Your Environment**
Angular Version: X.Y.Z
![image](https://user-images.githubusercontent.com/58823468/123159505-f424e500-d421-11eb-8e2f-a329ae38bbc8.png)

**Ticket Number**
IAEDEV-52067

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/58823468/123162109-0fddba80-d425-11eb-9138-ec6eb0e69262.png)

![image](https://user-images.githubusercontent.com/58823468/123162183-284dd500-d425-11eb-9c69-741c41113802.png)

**Comment by jesseboydgsa** [comment]
This functionality used to work and perhaps this commit caused the issue? https://github.com/GSA/sam-design-system/commit/bc8ad2b28350a95b1217f3c466f49333f7f44814#diff-8bbecea197e29920f29e40d78cf49e889916e5c3719c653594897cb7d37ed5a5

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa - Not sure I completely understand the setup. Can you reproduce on stackblitz. I started up a template with nested datepicker here - https://stackblitz.com/edit/angular-mks3ag?file=src%2Fapp%2Ffilters-optional.component.ts

**Comment by jesseboydgsa** [comment]
issue resolved with 10.0.34 update
