### ISSUE TITLE
Browser Back Button Issues - user cannot navigate back (out of search MFE) once filters are set

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#754]
**Components Involved**
search URL history tracking

**Expected Behavior**
When a user navigates from content MFE to Search MFE, selects a filter/search, then uses the browser back button > they should be able to navigate to the landing page they came from

**Actual Behavior**
Once the user sets filters and executes a search, they are stuck within the search MFE regardless of how many times they select the browser back button.

**Your Environment**
@gsa-sam/components@10.0.32
@gsa-sam/layouts@10.0.32
@gsa-sam/sam-material-extensions@10.0.32
@gsa-sam/sam-formly@10.0.32
@gsa-sam/sam-styles@0.0.114

**Ticket Number**
IAEDEV-51944

**Additional context**

**Comment by Bibek-Regmi** [comment]
Should be resolved as of 11.0.2
