### ISSUE TITLE
Types with optional dependencies need to marked OPTIONAL

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#755]
**Components Involved**
SearchSettings from @gsa-sam/components 
all types should be intentionally marked as required or optional

**Expected Behavior**
i expect when i run type checks that only required fields will be required

**Actual Behavior**
fields that are not required are causing type check failures

**Your Environment**
![image](https://user-images.githubusercontent.com/58823468/126403274-31c54d83-3a04-4dc4-ba17-a8ad08c90cf3.png)

**Ticket Number**
for all future development

**Additional context**

![image](https://user-images.githubusercontent.com/58823468/126403191-64bccbef-d52e-4bb0-b123-daaf3432dc9f.png)

I have brought this issue up specifically many times directly with design team developers

![image](https://user-images.githubusercontent.com/58823468/126403934-0834de2d-d952-48d8-bbc2-5b9df1294cd7.png)

**Comment by jesseboydgsa** [comment]
SearchSettings fixed with pr make optional params for SearchSettings optional #756 .  please keep this issue in mind for all types in design

**Comment by yerramshilpa** [comment]
Changes released in @gsa-sam/components@10.0.35 version
