### ISSUE TITLE
Sds-Filters inputs with numbers converted to dates on page reload

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#769]
**Components Involved**
SdsFilters  -> any input where numbers can be entered and saved as a chip.

**Expected Behavior**
for zip code and keyword for example i expect numbers to remain numbers and not be wrapped into a date.

**Actual Behavior**
any number between 1 and 6 digits is converted to a date.  1 - 123456
Numbers with letters are left alone.  this can be test 
1) From SDS demo, navigate to results layout or responsive layout demo page, type 1 in keyword, refresh page
 2) https://alpha.sam.gov/search/?index=_all  -> put 1 in keyword then refresh page

**Your Environment**
![image](https://user-images.githubusercontent.com/58823468/128746901-0c86e96e-4c27-4273-a5d2-d355cc73a923.png)

**Ticket Number**
IAEDEV-55547 

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/58823468/128747012-d2c0cc99-8648-45b1-95b5-876982e00583.png)
see number '123456' converted to date on page refresh

**Comment by yerramshilpa** [comment]
The issue has been resolved in @gsa-sam/ssam-formly@10.0.38 version
