### ISSUE TITLE
Mobile view - Apply button hidden on Iphones

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#774]
**Components Involved**

**Expected Behavior**
'Apply' button should be visible/within phone window to be selected

**Actual Behavior**
For iphones, the apply button appears to be hidden on the bottom of the screen. User can scroll to it, but phone re-adjusts to top of screen if user attempts to select button. There is workaround to  collapse the Filter header so button can appear on screen to be clicked

**Your Environment**
Angular Version: 10
@gsa-sam packages version: 10.0.35

**Ticket Number**
IAEDEV-55676

**Additional context**
![image](https://user-images.githubusercontent.com/79877133/129082195-fab8ade9-c768-49f6-bb7a-61a78b6f5633.png)

**Comment by rtencic-gsa** [comment]
Additional feedback provided by user with iphone 11 Max, More Filters is not available to select (below browser scroll similar to Apply button seen above).

![iphone11 - no filter or apply option](https://user-images.githubusercontent.com/79877133/129792626-43557ff4-46d8-49bf-adc9-ec4ad0bf9c6a.JPG)

**Comment by yerramshilpa** [comment]
This issue has been resolved in @gsa/sam-styles@0.0119 version
