### ISSUE TITLE
[508] Contrast Issue for step-indicator component

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#785]
**Components Involved**
step-indicator -> https://github.com/GSA/ngx-uswds/tree/main/src/app/step-indicator

WAVE testing shows a contrast issue for the current step when using the step-indicator component, as seen below. 

![wave-error-step-indicator](https://user-images.githubusercontent.com/74928453/130118815-2c2ef290-8b12-4f90-9069-33a4e4feeecd.PNG)

**Comment by Bibek-Regmi** [comment]
Resolved through sam-styles - https://github.com/GSA/sam-styles/pull/478
