### ISSUE TITLE
[508 Screen Reader] Tabbing through step-indicator not working when disabled. 

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#798]
**Components Involved**
usa-step-indicator: https://github.com/GSA/ngx-uswds/tree/main/src/app/step-indicator

**Expected Behavior**
The expectation is for a user to be able to tab through the step indicator even when it's disabled. (So screen readers will be able to pick up the elements). 

**Actual Behavior**
The step-indicator component is not picked up by the screen reader (JAWS) when tabbing through the page when disabled. 

**Your Environment**
Angular Version: 10.2.2
"@gsa-sam/layout": "10.0.54",
"@gsa-sam/layouts": "10.0.38",
"@gsa-sam/ngx-uswds": "0.0.1",
"@gsa-sam/ngx-uswds-icons": "0.0.4",
"@gsa-sam/sam-formly": "10.0.38",
"@gsa-sam/sam-material-extensions": "10.0.38",
"@gsa-sam/sam-styles": "0.0.116",
"@gsa-sam/shared": "10.0.33",

**Ticket Number**
https://cm-jira.usa.gov/browse/IAEDEV-56469

**Additional context**
Screen readers do not pick up disabled HTML elements.

One solution should work is to set the HTML as "readonly" when passed in the [disableStepSelection]="true" to the usa-step-indicator component. 

Another solution would be to allow for the user to pass in a 'tabindex' property to the UsaStepIndicatorModel (shown below), and then use that tabindex in the html. (First step would be tabindex=0, second would be tabindex=1, etc). 

![508-step-indicator](https://user-images.githubusercontent.com/74928453/131014349-e476d457-eabd-4c27-a72a-baa9b8b6a45f.PNG)

**Comment by Bibek-Regmi** [comment]
Disabled steps are also focusable - https://github.com/GSA/ngx-uswds/pull/6
