### ISSUE TITLE
508 Federal Entities Link in Workspace Toolbar

### ISSUE THREAD

**Issue by ClintMcCormick** [GSA/sam-design-system#844]
**Components Involved**
sds-card_subtitle

**Expected Behavior**
this element should have unique accessible name that is not the same as another one

**Actual Behavior**
this element should have unique accessible name that is not the same as another one

Angular Version: 11.2
@gsa-sam packages version: 11.0.7 (Please list individually if all packages are not same version)

**Ticket Number**
IAEDEV-58124

**Additional context**

![image](https://user-images.githubusercontent.com/66643502/136839138-b4977d3a-0546-4da1-bb2e-20898d05aea6.png)

![image](https://user-images.githubusercontent.com/66643502/136839161-72dc3aef-c5c5-46ac-ac35-11c7e7fe5ca6.png)

**Comment by Bibek-Regmi** [comment]
Closing due to no response
