### ISSUE TITLE
SDS-Filters not displayed correctly.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#860]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-filters
**Expected Behavior**
How you expect the listed component(s) to function
When i navigate to search page with query params that have hidden filters, the hidden filters should not be hidden anymore.

**Actual Behavior**
How the listed component(s) actually function
When i navigate to search page with query params that have hidden filters, the hidden filter values are set but they do not show up unless the user selects them from more filters.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
@gsa-sam/components: 11.0.8
@gas-sam/layout:11.0.4
@gas-sam/layouts:11.0.8
@gas-sam/sam-formly:11.0.8
@gas-sam/shared:11.0.3

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-59593

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by Bibek-Regmi** [comment]
Still an issue as of 11/23/2021

**Comment by Bibek-Regmi** [comment]
Dev team reported issue as persistent for hidden filters with nested children

**Comment by rtencic-gsa** [comment]
After testing with new libs, existing default filters are working, but the nested non default filters are still not opening as user logs into a fresh session with data saved in the non -default filters (ie. Published Date/inactive Date fitlers
