### ISSUE TITLE
ngx-uswds: side-navigation css styling

### ISSUE THREAD

**Issue by bserrano1** [GSA/sam-design-system#865]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is

Currently the side-navigation component contains no css or styling. 
https://gsa.github.io/ngx-uswds/side-navigation/examples

**Describe the desired solution**
Our current mock up requirement is as follows:
https://drive.google.com/drive/u/0/folders/1o3fDR401goRDOV913b5b5QaX8r3R-xqJ 
We would like the component to either match up or incorporate properties that will allow us to match our mock up design.

**Describe alternatives you've considered**

**Additional context**
https://github.com/GSA/ngx-uswds/tree/main/src/app/side-navigation

**Comment by cwolf10** [comment]
Stale, component in current demo site has styles.
