### ISSUE TITLE
/ngx-uswds/table

### ISSUE THREAD

**Issue by jamarjohnson2** [GSA/sam-design-system#866]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is

**Describe the desired solution**

**Describe alternatives you've considered**

**Additional context**

The table we are currently using is in black an white and is Striped and Compact. We want the component to have the same structure as our mockup currently. 

Table component below:
https://gsa.github.io/ngx-uswds/table/examples

Entity Team Mockups:
https://drive.google.com/drive/u/0/folders/1o3fDR401goRDOV913b5b5QaX8r3R-xqJ

Note: We would like the Table component listed to match the design of our tables in the design mockups.

**Comment by cwolf10** [comment]
Stale, reopen if this issue is still relevant.
