### ISSUE TITLE
Formly - x default

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#872]
**Components Involved**
Formly Auto-complete

**Expected Behavior**
Allow ability to set the default when 'x' is selected or allow anility to remove 'x'

**Actual Behavior**
when using 'x' filter defaults to blank (we have use case to default to a set 'select' option)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
IAEDEV-60462

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/79877133/142301904-883ece02-087f-4d03-8bb1-244de304b930.png)

**Comment by rtencic-gsa** [comment]
available to test in alpha at alpha.sam.gov/content/new-to-sam

**Comment by yerramshilpa** [comment]
Feature is released in @gsa-sam/components@11.0.16 version, documentation updated
