### ISSUE TITLE
508 - Date picker - Field label missing.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#882]
**Components Involved**
datepicker

**Expected Behavior**
Wave:Field label should be available and table header should not be Empty.
AMP: Use of placeholder values to label should be avoided.
Jaws: reader should read Date correctly.

**Actual Behavior**
Wave: Field label is missing and table header is Empty for datepicker  component
AMP: Placeholder value is used to label.
Jaws: When Draft account already have date, Jaws first reads the place holder value and then it reads the entered date.

**Your Environment**
Angular Version: 11.2
@gsa-sam/sam-formly : 11.0.4

**Ticket Number**
IAEDEV-60192

**Additional context**
Wave:
![image](https://user-images.githubusercontent.com/82841107/144631535-079e02ca-a9b3-43c3-a159-6143043ee134.png)

Open the Date picker and verify
![image](https://user-images.githubusercontent.com/82841107/144631641-de1f6eb9-f8a0-4f15-bf34-5aec573aac95.png)

AMP:
![image](https://user-images.githubusercontent.com/82841107/144631713-6c769140-8cf7-4f5c-94a0-bc7f742e7360.png)

![image](https://user-images.githubusercontent.com/82841107/144631747-a8a9fe8a-230b-446c-914a-ae205b91bc40.png)

**Comment by Bibek-Regmi** [comment]
Field Label issue resolved from application side. The issue regarding date picker table header is from Angular Material side and is false positive. The empty table header contains aria-hidden attribute that allows it to be ignored by accessibility tools
