### ISSUE TITLE
SDS - Horizontal Filters do not work correct with JAWS

### ISSUE THREAD

**Issue by rpsboyz** [GSA/sam-design-system#892]
**Components Involved**
Horizontal Filter

**Expected Behavior**
For the filter to expand when pressing space, as read by JAWS

**Actual Behavior**
JAWS states to press space, but this causes the page to drop down towards bottom of screen; only Enter key expands the filter

**Your Environment**
Angular Version: 11.2.14
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
@gsa-sam/components: 11.0.13
@gsa-sam/layout:11.0.5
@gsa-sam/layouts:11.0.12
@gsa-sam/ngx-uswds:^0.0.7
@gsa-sam/ngx-uswds-icons:0.0.7
@gsa-sam/sam-formly:11.0.13
@gsa-sam/sam-material-extensions:11.0.13
@gsa-sam/sam-styles:0.0.120
@gsa-sam/sam-ui-elements:3.0.1
@gsa-sam/shared:11.0.3

**Ticket Number**
IAEDEV-62335

**Additional context**
Audio/Video recording link in the 'Description' section of the ticket listed above.

**Comment by yerramshilpa** [comment]
@rpsboyz  Issue has been fixed and released in @gsa-sam/components@11.0.20 version

**Comment by rpsboyz** [comment]
@yerramshilpa I verified this on the 'SAM.Gov - Design System Components' page and pressing space works as spoken by JAWS.
I will have our Dev bring this updated component into our new MFE Admin Following page and validate.

**Comment by rpsboyz** [comment]
@yerramshilpa I coordinated with my Dev team and they brought in the updated Horizontal Filter Component. I recorded the screen to show that pressing space now expands the button as read by JAWS. I have updated my Jira ticket. You can now close out your side. Thanks for all of your help.
