### ISSUE TITLE
sds auto complete - 508 - user is unable to make selection using keyboard keys. 

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#894]
Components Involved
Sds auto complete

Expected Behavior
User should be able to make selection using keyboard keys 

Actual Behavior
User is unable to make selection from the auto complete using keyboard keys (tried Enter, Space, up and down arrow keys)

Angular Version: 11
@gsa-sam packages version: 11.0.19

Ticket Number
IAEDEV-43744

![image](https://user-images.githubusercontent.com/82841107/149403058-d8f352ef-0441-434a-af68-3eaea22892b3.png)

![image](https://user-images.githubusercontent.com/82841107/149403252-ed324900-fe34-4c1d-8209-05529ed799a1.png)

**Comment by yerramshilpa** [comment]
@Parulbpatel Issue has been fixed and released in @gsa-sam/components@11.0.20 version
