### ISSUE TITLE
SDS - Horizontal Filters - Value Names in Drop-Down are Not Spoken By JAWS and Space Not working on Check-box

### ISSUE THREAD

**Issue by rpsboyz** [GSA/sam-design-system#901]
Components Involved
Horizontal Filter

Expected Behavior
When Tabbing to values in drop-down menu, JAWS should speak the name of the value(s) tabbed to. Also, when pressing Space to check a box, it should check-mark it and speak that the value name that was checked

Actual Behavior
JAWS only speaks a count of values listed; when pressing space to select a check-box, it collapses the drop-down menu

Your Environment
Angular Version: 11.2.14
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
gsa-sam/components@11.0.20

Ticket Number
IAEDEV-63501

Additional context
Audio/Video recording link in the 'Description' section of the ticket listed above.

**Comment by yerramshilpa** [comment]
The issue has been resolved and released in @gsa-sam/components@11.0.22
