### ISSUE TITLE
SDS - Horizontal Filter - JAWS Not Speaking Names When Closing Filtered Values

### ISSUE THREAD

**Issue by rpsboyz** [GSA/sam-design-system#902]
Components Involved
Horizontal Filter

Expected Behavior
When Tabbing to filtered values, JAWS should speak the name of the value(s) tabbed to so the sight impaired user knows what value they are on

Actual Behavior
JAWS only speaks ‘Remove item Status left-bracket object object right bracket button, to activate press Enter’ but does not name the Status value you are un-filtering

Your Environment
Angular Version: 11.2.14
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
gsa-sam/components@11.0.20

Ticket Number
IAEDEV-63502

Additional context
Audio/Video recording link in the 'Description' section of the ticket listed above.

**Comment by yerramshilpa** [comment]
The issue has been resolved and released in @gsa-sam/components@11.0.22

**Comment by rpsboyz** [comment]
Shilpa, I tested this particular defect and JAWS still only speaks 'Remove item Status left-bracket object object right bracket button, to activate press Enter’ but does not name the Status value being un-filtered.

**Comment by rpsboyz** [comment]
@yerramshilpa notified me to re-test this morning after fix. I re-tested on Design system components page with JAWS and it is now working properly.

**Comment by yerramshilpa** [comment]
This issue has been resolved in @gsa-sam/components@11.0.23

**Comment by rpsboyz** [comment]
Shilpa, can you please verify that package @gsa-sam/components@11.0.23 has been released? My Dev said they updated the package and pushed to COMP but it still gives me the same 'Remove item Domain left-bracket object object right bracket button, to activate press Enter’ message when running JAWS

**Comment by yerramshilpa** [comment]
Yes, it's released in @gsa-sam/components@11.0.23 and you confirmed me its working on the SDS..Can you try with latest version @gsa-sam/components@11.0.26, if it still exist can you reopen the issue

**Comment by rpsboyz** [comment]
Shilpa, our Dev updated the package to @gsa-sam/components@11.0.26 and pushed to COMP environment; however, it JAWS still speaks it with "Remove item Domain left-bracket object object right bracket button, to activate press Enter".
video recording with JAWS located at https://drive.google.com/file/d/1rE3pZ7A89Qr8h_bW_aCh_X0H0c7oacsD/view?usp=sharing (I gave you access to this file)
