### ISSUE TITLE
508 - Tree Table in Entire Hierarchy and All Sam Entity page

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#911]
**Components Involved**
Tree Table

**Expected Behavior**
Wave: There should not be any contrast error 
AMP: There should not be any violations.

**Actual Behavior**
Wave tool shows contrast error for Tree Table comp – class: usa-sr-only 
AMP tool shows confirmed violations.

**Your Environment**
Angular Version: 11.2
@gsa-sam packages version: 11.0.20 

**Ticket Number**
IAEDEV-58997, IAEDEV-61574

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
Please see attached for AMP Report.

![image](https://user-images.githubusercontent.com/82841107/152404103-63f7ebad-fe5b-4a62-8398-1ca21ed9dc69.png)

[
[508_AMP Report.xls](https://github.com/GSA/sam-design-system/files/8063711/508_AMP.Report.xls)

](![image](https://user-images.githubusercontent.com/82841107/153940403-065ef5b4-9cf8-4940-8b99-a6819ece19cb.png))

**Comment by cwolf10** [comment]
Hi,

I just ran an AMP test on our tree-table demo. In my results there is no error regarding the table header cell, so I imagine this has been resolved in the past.

On the contrast error, it is highlighting text with the `usa-sr-only` class. The whole point of this class is to visually hide text but make it available for screen-readers. There is nothing to change.
