### ISSUE TITLE
Mobile friendly carousel component

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#914]
**Is your feature request related to a problem? Please describe.**
We have carousel component that is not mobile friendly with limited title spacing

**Describe the desired solution**
To align mockup for carousel with expected mobile version of

**Describe alternatives you've considered**
Changing mobile view to not use carousel, or update custom component to show only one header at a time with ability to click to next header

**Additional context**
Screenshot of existing custom component in mobile view

![image](https://user-images.githubusercontent.com/79877133/153914435-271c0cca-f50e-44e8-a15b-6ad69dc1ed2e.png)

**Comment by davereed** [comment]
No longer needed, using stepper component instead.
