### ISSUE TITLE
Autocomplete Combobox Access Assistant error

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#917]
**Components Involved**
formly-form

**Expected Behavior**
Autocomplete combobox passes Access Assistant checks.

**Actual Behavior**
Access Assistant error: "This INPUT (role=combobox) must have all of the following attributes: aria-controls | aria-expanded"

**Your Environment**
Angular Version: 11.2.14
@gsa-sam packages version: 11.0.20

**Ticket Number**
TBD

**Additional context**

<img width="841" alt="image" src="https://user-images.githubusercontent.com/75684861/154144239-7bc6af45-06c9-45a9-a022-801a4ab06038.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/75684861/154144399-1aaa9f40-108f-4107-b65d-f84d35c40bf5.png">

**Comment by yerramshilpa** [comment]
The AMP issue is fixed in the @gsa-sam/components@11.0.25 version
