### ISSUE TITLE
Stepper Component - Background Color and Mobile View

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#918]
**Components Involved**
Stepper 

**Expected Behavior**
1) Component to have transparent background to sit within a an image/div with color for smoother look

2) Mobile version of stepper to have counter indicating what step user is on

**Actual Behavior**
1) component has white background color

2) Counter missing in mobile view

**Your Environment**
Angular 11

@gsa-sam/components@11.0.19
@gsa-sam/sam-material-extensions@11.0.19
@gsa-sam/sam-formly@11.0.19

**Ticket Number**
IAEDEV-62905

**Additional context**
Image from SDS site:
![image](https://user-images.githubusercontent.com/79877133/154485722-7df07e20-d052-4fe1-b857-c84cade34648.png)

**Comment by yerramshilpa** [comment]
Issue has been released in @gsa-sam/sam-styles@0.0.132 version.
