### ISSUE TITLE
Request to add Disable feature to Action Items Menu

### ISSUE THREAD

**Issue by navyasreekumbam-reisys** [GSA/sam-design-system#933]
We have a requirement to disable certain actions on a given record until some specific actions are performed under the actions Menu

We will need to hot-fix this requirement to 38.2 deployment. As of now we are hiding the actions, once the disable option is available in the component we will hot-fix the disable logic instead of hiding action items.

**Comment by yerramshilpa** [comment]
The new feature implemented and added documentation for in the sds documentation under action menu and released in @gsa-sam/components@12.0.0
