### ISSUE TITLE
Adding a header to the table component

### ISSUE THREAD

**Issue by RajiRadwan** [GSA/sam-design-system#936]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is
We got a new requirement for Other Responsibility Information Table, To have a higher level header 'Responsibility Record' 
**Describe the desired solution**
A higher level header that spans on every column and have a table title 
**Describe alternatives you've considered**
We tried to alter the table in number different ways all of which it had no effort on the desired structure.  
**Additional context**
![image](https://user-images.githubusercontent.com/93665144/159980384-e1e0c87e-6b5f-4735-9d0a-43e62272f6e5.png)

**Comment by RajiRadwan** [comment]
we go the requirement to have the Responsibility Record at a higher level header so the table wont look redundant. so if you have any other solution that you can propose please let us know, or if you can share this with your PO if they have any solution for this. Thank you.

**Comment by cwolf10** [comment]
Stale, please reopen if this issue is still relevant.
