### ISSUE TITLE
Date picker - ATO Expiry Date placeholder text got changed.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#940]
**Components Involved**
datepicker

**Expected Behavior**
ATO Expiration Date placeholder text should show eg. date

**Actual Behavior**
ATO Expiration Date: Choose Date's placeholder text is showing "to.placholder ? to.placeholder :"

**Your Environment**
Angular Version:@angular/core : 12.2.20, @angular/material : 12.2.13, Module : SdsFormlyModule
@gsa-sam packages version: @gsa-sam/sam-formly : 12.0.0-beta.7

**Ticket Number**
IAEDEV-65418

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Before:**
![image](https://user-images.githubusercontent.com/82841107/160409946-ec04cef7-3a38-4b38-b85a-b9a77a78cd7e.png)

**Issue:**

![image](https://user-images.githubusercontent.com/82841107/160410733-1f3ce20a-47e5-4839-ab54-6fefd3ed46b9.png)

**Comment by yerramshilpa** [comment]
@Parulbpatel  issue was resolved and released in @gsa-sam/formly@12.0.0 version

**Comment by Parulbpatel** [comment]
Thanks Shilpa
