### ISSUE TITLE
Hourglass Icon disappeared 

### ISSUE THREAD

**Issue by addiedavis** [GSA/sam-design-system#945]
**Components Involved**
When updating libraries up through Angular 12 libraries the sds-search components no longer show the hourglass icon.

**Expected Behavior**
using the sds-search component shows the hourglass icon inside a blue box to the right of the text box.
Please see https://cg-fa19003e-5296-4960-ac2e-caccfeb620ac.app.cloud.gov/site/gsa/sam-design-system/documentation/components/search/examples 
![image](https://user-images.githubusercontent.com/32769685/161805648-86dce2ff-3783-422e-b935-919d91e054e4.png)
(image taken from IAEDEV-64519 design image: Home_Page_IP38.pdf)

**Actual Behavior**
when using hte sds-search component a blue box appears without the hourglass icon to the right of the text box
![image](https://user-images.githubusercontent.com/32769685/161804217-cd8dcacd-0cab-4a8d-835c-5c15a1ffd616.png)

**Your Environment**
Angular Version: 12
@gsa-sam/components: 12.0.0-beta.8
@gsa-sam/layout: 12.0.1
@gsa-sam/layouts: 12.0.1
@gsa-sam/ngx-uswds: 12.0.0-beta.7
@gsa-sam/ngx-uswds-icons: 12.0.0-beta.2
@gsa-sam/sam-formly: 12.0.0-beta.8
@gsa-sam/sam-material-extensions: 12.0.0-beta.8
@gsa-sam/sam-styles: 0.0.132
@gsa-sam/shared: 12.0.1
![image](https://user-images.githubusercontent.com/32769685/161804618-d7c89b03-2f9d-4cb8-8c43-ac600239d809.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-67294

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
Issue resolved in @gsa-sam/components@12.0.1 version, also there is a angular 11 version @gsa-sam/components@11.0.28 version for the production issue
