### ISSUE TITLE
SdsStepper - When there is a validation error message for a field, then the field spacing is reduced.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#948]
**Components Involved**
SdsStepper

**Expected Behavior**
When there is a validation error message for a field, then the spacing in between the fields should be correct.

**Actual Behavior**
when the page has multiple fields, and if there is a validation error message for a field, then the field position shifts up and the spacing is reduced.

**Your Environment**
Angular Version: 12.0.0-beta.9 ,This is happening in Angular 11 version also
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
IAE-66991

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/82841107/162046739-08ebf453-19d0-4f7d-8e1f-836afb2c7eb3.png)

![image](https://user-images.githubusercontent.com/82841107/162046773-aacb2035-7a27-4531-8b70-43eac8a880bb.png)

**Comment by yerramshilpa** [comment]
@Parulbpatel the issue resolved in @gsa-sam/sam-styles@0.0.134
