### ISSUE TITLE
SdsStepper - On Permissions tab, unable to display error message and lot of spacing between domains.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#949]
**Components Involved**
SdsStepper

**Expected Behavior**
On the Permissions tab:
1) When user does not select any permission, one error message at the top level should be displayed.
2) There should not be lot of spacing between individual Domains.

**Actual Behavior**
On the Permissions tab:
1) When user does not select at least one permission, unable to display one error message at the top level. 
2) There is a lot of spacing between individual Domains.

**Your Environment**
Angular Version: 12.0.0-beta.9 ,This is happening in Angular 11 version also

**Ticket Number**
IAE-66991

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/82841107/162048430-2de525f9-b4b1-4240-8511-68b04495456f.png)

![image](https://user-images.githubusercontent.com/82841107/162048471-2b03f6bd-2589-45cc-a139-22530d394f37.png)

**Comment by yerramshilpa** [comment]
@Parulbpatel  Issue has been resolved and released @gsa-sam/sam-styles@0.0.137 and @gsa-sam/sam-formly@12.0.4
.
