### ISSUE TITLE
Extra margin on top of multi-checkbox

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#955]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
Formly-multicheckbox

**Expected Behavior**
How you expect the listed component(s) to function
There is extra space on the top checkbox which does not look good when using in an accordion.
![image](https://user-images.githubusercontent.com/92172714/163190255-9ff701a8-3cc5-44a5-ade0-8b5ed2a93990.png)
![image](https://user-images.githubusercontent.com/92172714/163190769-b9ab74c6-63e1-4d87-bcd6-2abee16e83ed.png)

**Actual Behavior**
How the listed component(s) actually function
Should have that extra margin or padding on the top checkbox.

**Your Environment**
Angular Version: 12.2.5
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
@gsa-sam/components: 12.0.0-beta.7
@gas-sam/layout:12.0.1
@gas-sam/layouts:12.0.1
@gas-sam/sam-formly:12.0.0-beta.7
@gas-sam/shared:12.0.1

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-63263

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by yerramshilpa** [comment]
@knamburigsa Issue is resolved in @gsa-sam/sam-formly@12.0.4 and also need to update @gsa-sam/sam-styles@0.0.137 version, both needs to be updated
