### ISSUE TITLE
[508 Defect] Contrast issue on Usa Step Indicator

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#964]
WAVE testing shows a contrast issue for the current step when using the step-indicator component, as seen below.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/74928453/167220076-8ff9e3e1-9859-4a74-90f4-ff0a10256b89.png">

**Comment by cwolf10** [comment]
With foreground #2672DE and background #EEF6FA the contrast ratio is 4.22:1

**Comment by alexkamien** [comment]
@cwolf10 does this mean the contrast is okay? Or is this recognized as an issue that will be fixed?

**Comment by cwolf10** [comment]
Not a component issue as the blue background is not coming from the stepper.
