### ISSUE TITLE
sdsTable - Change icon for expanded indicator.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#968]
**Components Involved**
sdsTable
**Expected Behavior**
On the Saved Searches results display, user should be able to see the ‘+’ or the ‘-‘ icon next to the saved search.

**Actual Behavior**
On the Saved searches results display, if we enable the expanded Indicator column, the default icons are chevron-up and chevron-down.
**Your Environment**
Angular Version: 12.0.0-beta.9, current version of the sdsTable implementation has the chevron-up and chevron-down icons.

**Ticket Number**
IAEDEV-68324

**Additional context**
Current screen:
![image](https://user-images.githubusercontent.com/82841107/167687824-56c8da80-1c59-41c7-ade5-ca84e1ea406d.png)

Required design screenshot:
![image](https://user-images.githubusercontent.com/82841107/167687877-0d189711-2fbf-4c3e-ac0d-215635b26633.png)

**Comment by yerramshilpa** [comment]
@Parulbpatel  Icon are changed to plus/minus, and released in the @gsa-sam/sam-material-extensions@12.0.4 version
