### ISSUE TITLE
sdsTable - Extra margins on top and side boundary of expansion column for sdsTable

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#969]
**Components Involved**
SdsTable

**Expected Behavior**
There should be no extra margins.

**Actual Behavior**
There is extra margin on top and side boundary for sdsTable component which does not look good.
![image](https://user-images.githubusercontent.com/82841107/167927949-c3e1b29b-c465-4087-a2c5-5f2161e9c2b5.png)

When implementing to move the column to the beginning of the table, the extra margin gets carried over:
![image](https://user-images.githubusercontent.com/82841107/167928009-171b9dc4-02a3-48f7-ab6d-9c4876566519.png)

**Your Environment**
Angular Version: 12.0.0-beta.9, current version of the sdsTable implementation has the extra margins.

**Ticket Number**
IAE-68324

**Additional context**
Detailed above.

**Comment by yerramshilpa** [comment]
Issue fixed and changes released in @gsa-sam/sam-material-extensions@12.0.5
