### ISSUE TITLE
Color/position of close Dialog (Slideout)

### ISSUE THREAD

**Issue by thomastighe** [GSA/sam-design-system#972]
It looks like there is a need to make the color configurable for the close button

https://github.com/GSA/sam-design-system/blob/83b72282e9d79b44457d0d2ed2cde764ea02e33b/libs/packages/components/src/lib/dialog/dialog-container.component.html#L1

**Comment by yerramshilpa** [comment]
@thomastighe we don't need to make any component changes for the slide button color changes. 

Here is the example added for the slideout custom header demo.
