### ISSUE TITLE
sds-modal-sample Design of the popup modal and color of the font text

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#974]
**Components Involved**
Dialog modal : sds-modal-sample
Inside the popup :  component SelectBasic

**Expected Behavior**
 On the updated saved search results page(new) ,when you click on the bell icon/notify icon the pop up modal dialog appears.
The pop -up modal appears more curvier (meaning the edges are more curvier ), 
Trying to achieve the highlighted  blue text color.

**Actual Behavior**
The current modal dialog is more like a box and the text font and color

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: "@gsa-sam/sam-formly": "12.0.2"

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE- 68324

**Additional context**
![image](https://user-images.githubusercontent.com/82841107/169599117-988b67c9-762f-4b83-96f1-4aadf642e4b5.png)

**Comment by cwolf10** [comment]
Stale, please reopen if this issue is still relevant.
