### ISSUE TITLE
Formly Form Search - advanced search link

### ISSUE THREAD

**Issue by addiedavis** [GSA/sam-design-system#976]
**Is your feature request related to a problem? Please describe.**
The Formly Search component is often used in SAM.gov with an added 'advanced search' link above the search bar.
The advanced search link is currently being added manually for each instance.
It would be nice to have the formly search form be able to handle a template option to add in the 'advanced search' link.

**Describe the desired solution**
I would like to add into the search templateOptions the following attributes:
'advancedSearch': boolean (default false)
'advancedSearchUrl': string 

When advancedSearch === 'true' then the form should add a link saying 'Advanced Search' to the right of the label and above the hourglass icon
The link would use the 'advancedSearchUrl' provided as the href

**Describe alternatives you've considered**
Currently we add in a header above the formly form and that adds in a large gap between the search bar and what would have been the label for the search bar. 

**Additional context**
This is how our current solution looks. 
The gap is frustratingly different from the normal formly component's label 

![image](https://user-images.githubusercontent.com/32769685/170052076-5f1ebaf4-c53f-486f-ba0e-0cfcc493f3ce.png)

**Comment by cwolf10** [comment]
Stale, please reopen if this issue is still relevant.
