### ISSUE TITLE
saved search formly modal - checkbox and input field dropdown is not fully visible.

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#979]
**Components Involved**
saved search formly modal

**Expected Behavior**
checkbox and input field dropdown should be fully visible

**Actual Behavior**
The wrapper is not large enough around the checkbox and it gets cut off. I have tried changing the
minimum size of the formly field but it did not work.

**Your Environment**
Angular Version: 12.0.0-beta.9, current version of the formly modal implementation

**Ticket Number**
IAE-68429

**Additional context**
![image](https://user-images.githubusercontent.com/82841107/171652975-9b400c88-0c86-4917-9a67-3908e89b2472.png)

**Comment by yerramshilpa** [comment]
Issue is resolved and  released in @gsa-sam/sam-formly@12.0.6 version
