### ISSUE TITLE
date-picker, maxDate validation error

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#982]
**Components Involved**
formly of type 'date-picker'

**Expected Behavior**
If maxDate is passed in as today, and the user manually enters a date in the future, validation message should say something along the lines of; "Date must be on or before 6/6/2022. (If today's date is 6/6/2022). 

**Actual Behavior**
Currently in this scenario, validation message shows "Date must be before 6/6/2022" 

**Your Environment**
Angular Version: 12.2.15
 "@gsa-sam/components": "12.0.4",
  "@gsa-sam/layout": "12.0.1",
  "@gsa-sam/layouts": "12.0.6",
  "@gsa-sam/ngx-uswds": "12.0.0",
  "@gsa-sam/ngx-uswds-icons": "12.0.0-beta.2",
  "@gsa-sam/sam-formly": "12.0.4",
  "@gsa-sam/sam-material-extensions": "12.0.4",
  "@gsa-sam/sam-styles": "0.0.138",
  "@gsa-sam/shared": "12.0.12",

**Ticket Number**
IAEDEV-68142

**Additional context**

Code used for configuring the date-picker; 
{
  key: 'startDate',
  type: 'datepicker',
  templateOptions: {
    label: 'Start Date',
    hideOptional: true,
    required: true,
    maxDate: new Date(),
    placeholder:
    'eg: ' +
    new Date().toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    }),
  },
},

### **Scenario; today's date is properly being accepted by the component**
<img width="348" alt="Screen Shot 2022-06-06 at 9 40 26 AM" src="https://user-images.githubusercontent.com/74928453/172185775-269e1204-dbcf-4c90-b1cb-96f69a3aa0f8.png">
<img width="277" alt="Screen Shot 2022-06-06 at 9 39 22 AM" src="https://user-images.githubusercontent.com/74928453/172185798-595f10db-68e7-4800-83fc-c9dfeb743008.png">

### **Scenario; if date above max date is entered manually by user, validation error shown**
<img width="288" alt="Screen Shot 2022-06-06 at 9 39 41 AM" src="https://user-images.githubusercontent.com/74928453/172186226-07d9a3d5-6433-4ffd-a456-b118bf94073e.png">

**Comment by yerramshilpa** [comment]
The issue resolved and released in sam-formly@12.0.7
