### ISSUE TITLE
OnModalChange in SDSFilters being invoked twice when using templateOptions.disbaled config.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#999]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
 SdsFiltersComponent - github.com/GSA/sam-design-system/blob/master/libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts#L241

**Expected Behavior**
How you expect the listed component(s) to function
When a field is disabled or enabled based on templateOptions.disabled property and when this is returned false, sds-filters component should not invoke on modal change twice.

**Actual Behavior**
How the listed component(s) actually function
When a field is disabled or enabled based on templateOptions.disabled property and when this is returned false, sds-filters component invoking the onModalChange twice. Which is resulting in multiple calls to our backend service.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-1239

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
I added console log to onModelChange method. https://github.com/GSA/sam-design-system/blob/master/libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts#L241
With templateOptions.disbaled Set:
![image](https://user-images.githubusercontent.com/92172714/178004049-a1701277-44b7-4391-909e-252526f6b995.png)

![image](https://user-images.githubusercontent.com/92172714/178003284-b8c9b48e-c9e7-4c35-a0ee-01aa541c94d6.png)

With templateOptions.disabled not configured:
![image](https://user-images.githubusercontent.com/92172714/178003987-2c91497b-16d9-4b9c-9da1-0d91899d1191.png)

![image](https://user-images.githubusercontent.com/92172714/178003868-0e5c423f-bb4c-446c-b88b-46f3d588df0f.png)

This is happening for any field that is using this config.

**Comment by yerramshilpa** [comment]
The issue is not related to the sds-filters.
